In [7]:
import pandas as pd
df=pd.read_csv("C:/Users/Ayushee/Dropbox/Columbia/Spring 2019/Business Analytics/Group Project/gentrification_yelp-master/gentrification_yelp-master/ny_rent_studio.csv")
df

,Unnamed: 0,RegionName,City,State,Metro,CountyName,SizeRank,2011-11,2011-12,2012-01,...,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,%_increase
0,0,10025,New York,NY,"New York, NY",New York,1,1900.0,1900.0,1895.0,...,2618.0,2600.0,2600.0,2695.0,2625.0,2650.0,2700.0,2659.5,2450.0,28.947368
1,1,10023,New York,NY,"New York, NY",New York,3,2295.0,2200.0,2292.5,...,2800.0,2893.0,2900.0,2800.0,2800.0,2850.0,2800.0,2770.0,2695.0,17.429194
2,2,10002,New York,NY,"New York, NY",New York,6,NaN,NaN,NaN,...,2400.0,2272.5,2199.0,2199.5,2227.5,2500.0,2500.0,2295.0,2312.5,NaN
3,3,11226,New York,NY,"New York, NY",Kings,10,NaN,NaN,NaN,...,1500.0,1597.0,1550.0,1525.0,1525.0,1550.0,1550.0,1645.0,1600.0,NaN
4,4,11375,New York,NY,"New York, NY",Queens,11,1325.0,1300.0,1300.0,...,1695.0,1690.0,1725.0,1800.0,1800.0,1795.0,1785.0,1695.0,1925.0,45.283019
5,5,10016,New York,NY,"New York, NY",New York,12,2300.0,2275.0,2299.5,...,2695.0,2750.0,2750.0,2787.5,2795.0,2800.0,2775.0,2775.0,2750.0,19.565217
6,6,11235,New York,NY,"New York, NY",Kings,13,NaN,NaN,NaN,...,1700.0,1695.0,1550.0,1650.0,1699.5,1700.0,1632.5,1695.0,1725.0,NaN
7,7,10009,New York,NY,"New York, NY",New York,14,1900.0,1900.0,1925.0,...,2100.0,2100.0,2100.0,2136.0,2150.0,2199.0,2195.0,2150.0,2200.0,15.789474
8,8,10029,New York,NY,"New York, NY",New York,15,NaN,NaN,NaN,...,2800.0,2750.0,2775.0,2800.0,2750.0,2800.0,2812.5,2800.0,2750.0,NaN
9,9,10128,New York,NY,"New York, NY",New York,16,1950.0,1900.0,1875.0,...,2250.0,2249.0,2150.0,2175.0,2200.0,2179.0,2150.0,2150.0,2137.5,9.615385
10,10,10011,New York,NY,"New York, NY",New York,17,2500.0,2500.0,2490.0,...,2860.0,2850.0,2850.0,2895.0,2900.0,2900.0,2950.0,2950.0,2950.0,18.000000
11,11,10003,New York,NY,"New York, NY",New York,22,2495.0,2350.0,2375.0,...,2675.0,2700.0,2725.0,2800.0,2800.0,2700.0,2800.0,2750.0,2695.0,8.016032
12,12,11209,New York,NY,"New York, NY",Kings,30,NaN,1100.0,1100.0,...,1450.0,1650.0,1605.0,1575.0,1497.5,1672.5,1695.0,1750.0,1725.0,NaN
13,13,11201,New York,NY,"New York, NY",Kings,31,NaN,NaN,2200.0,...,2500.0,2562.0,2542.0,2564.0,2543.0,2584.0,2666.0,2715.0,2704.0,NaN
14,14,10024,New York,NY,"New York, NY",New York,34,2095.0,2100.0,2025.0,...,2397.5,2330.0,2350.0,2395.0,2400.0,2450.0,2400.0,2437.5,2397.5,14.439141
15,15,11214,New York,NY,"New York, NY",Kings,37,NaN,NaN,NaN,...,1750.0,1750.0,1787.5,1875.0,1900.0,2000.0,2000.0,1950.0,1800.0,NaN
16,16,11234,New York,NY,"New York, NY",Kings,43,NaN,NaN,NaN,...,1800.0,2050.0,2000.0,2000.0,2000.0,2250.0,2000.0,2000.0,1950.0,NaN
17,17,10019,New York,NY,"New York, NY",New York,44,2500.0,2497.5,2500.0,...,2900.0,2880.0,2900.0,2925.0,2900.5,3000.0,2995.0,3000.0,3010.0,20.400000
18,18,11355,New York,NY,"New York, NY",Queens,48,1253.0,1350.0,1300.0,...,1700.0,1725.0,1700.0,1700.0,1950.0,2100.0,2050.0,1950.0,1900.0,51.636073
19,19,11215,New York,NY,"New York, NY",Kings,52,NaN,NaN,NaN,...,2300.0,2500.0,2369.0,2300.0,2250.0,2200.0,2225.0,2200.0,2400.0,NaN
20,20,11221,New York,NY,"New York, NY",Kings,53,1435.0,1450.0,1350.0,...,1950.0,2000.0,1800.0,1800.0,1850.0,2000.0,2175.0,1999.5,2000.0,39.372822
21,21,11211,New York,NY,"New York, NY",Kings,60,2250.0,2400.0,2600.0,...,2830.0,2745.0,2745.0,2710.0,2750.0,2750.0,2692.5,2750.0,2790.0,24.000000
22,22,11373,New York,NY,"New York, NY",Queens,61,1195.0,1195.0,1225.0,...,1472.5,1550.0,1650.0,1605.0,1512.0,1475.0,1500.0,1581.0,1600.0,33.891213
23,23,11385,New York,NY,"New York, NY",Queens,61,NaN,NaN,NaN,...,2150.0,2300.0,2000.0,2075.0,2000.0,2000.0,2000.0,2050.0,2100.0,NaN
24,24,10028,New York,NY,"New York, NY",New York,66,1895.0,1875.0,1865.0,...,1995.0,2063.0,2095.0,2100.0,2095.0,2150.0,2125.0,2100.0,2100.0,10.817942
25,25,10027,New York,NY,"New York, NY",New York,75,NaN,NaN,NaN,...,2025.0,2100.0,2250.0,2147.5,2015.5,1950.0,1895.0,2025.0,2045.5,NaN
26,26,10021,New York,NY,"New York, NY",New York,86,1900.0,1900.0,1895.0,...,2177.5,2104.0,2150.0,2150.0,2195.0,2250.0,2225.0,2200.0,2100.0,10.526316
27,27,11208,New York,NY,"New York, NY",Kings,96,NaN,NaN,NaN,...,2100.0,2100.0,2100.0,2100.0,2175.0,2125.0,2124.5,2325.0,2200.0,NaN
28,28,11204,New York,NY,"New York, NY",Kings,106,NaN,NaN,NaN,...,1775.0,1975.0,1800.0,1800.0,1600.0,1600.0,1775.0,1800.0,1950.0,NaN
29,29,10032,New York,NY,"New York, NY",New York,108,NaN,NaN,NaN,...,1527.5,1595.0,1595.0,1557.0,1620.0,1645.0,1645.0,1600.0,1600.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,42,10065,New York,NY,"New York, NY",New York,313,2495.0,2337.5,2295.0,...,2730.0,2695.0,2795.0,2700.0,2700.0,2762.5,2850.0,2800.0,2625.0,5.210421
43,43,11435,New York,NY,"New York, NY",Queens,338,NaN,NaN,NaN,...,1475.0,1475.0,1499.0,1599.5,1675.0,1695.0,1600.0,1612.5,1599.5,NaN
44,44,11205,New York,NY,"New York, NY",Kings,357,NaN,NaN,NaN,...,2350.0,2380.0,2261.0,2261.0,2352.0,2397.5,2395.0,2397.5,2400.0,NaN
45,45,11217,New York,NY,"New York, NY",Kings,399,NaN,NaN,NaN,...,2535.0,2431.5,2340.0,2350.0,2580.0,2655.0,2745.0,2723.0,2710.0,NaN
46,46,11365,New York,NY,"New York, NY",Queens,401,NaN,NaN,NaN,...,2400.0,2300.0,2300.0,2297.5,2200.0,2300.0,2375.0,2450.0,2500.0,NaN
47,47,10035,New York,NY,"New York, NY",New York,428,1787.0,1742.5,1650.0,...,1850.0,1743.5,1855.0,1795.0,1772.5,1850.0,1795.0,1922.5,1885.0,5.484051
48,48,10075,New York,NY,"New York, NY",New York,433,1775.0,1775.0,1750.0,...,2000.0,1950.0,1973.5,1997.0,1995.0,2000.0,2075.0,2075.0,2050.0,15.492958
49,49,11102,New York,NY,"New York, NY",Queens,434,NaN,NaN,NaN,...,2000.0,2050.0,2000.0,2000.0,1932.0,1995.0,1837.5,2100.0,2100.0,NaN
50,50,11101,New York,NY,"New York, NY",Queens,439,NaN,NaN,NaN,...,2235.0,2251.0,2238.5,2271.0,2315.0,2347.5,2416.0,2418.0,2400.0,NaN
51,51,10001,New York,NY,"New York, NY",New York,466,NaN,NaN,NaN,...,2987.5,3037.0,2995.5,2907.0,2999.5,3177.0,3080.0,3077.0,3074.5,NaN
52,52,10012,New York,NY,"New York, NY",New York,472,NaN,NaN,2350.0,...,2750.0,2750.0,2800.0,2892.5,2895.0,3000.0,2890.0,2882.5,2870.0,NaN
53,53,11249,New York,NY,"New York, NY",Kings,488,NaN,NaN,NaN,...,2865.0,2995.0,2995.0,2939.5,2950.0,2953.0,2950.0,3193.0,3200.0,NaN
54,54,11357,New York,NY,"New York, NY",Queens,512,NaN,NaN,NaN,...,2300.0,2200.0,2200.0,2200.0,2200.0,2225.0,2300.0,2300.0,2300.0,NaN
55,55,11358,New York,NY,"New York, NY",Queens,580,NaN,NaN,NaN,...,2200.0,2200.0,2200.0,2100.0,2147.5,2300.0,2300.0,2300.0,2300.0,NaN
56,56,10030,New York,NY,"New York, NY",New York,583,NaN,NaN,NaN,...,1537.5,1627.5,1550.0,1550.0,1625.0,1600.0,1695.0,1600.0,1595.0,NaN
57,57,10017,New York,NY,"New York, NY",New York,617,2300.0,2200.0,2200.0,...,2497.0,2500.0,2550.0,2580.0,2575.0,2580.0,2600.0,2650.0,2600.0,13.043478
58,58,10038,New York,NY,"New York, NY",New York,630,2516.5,2550.0,2550.0,...,2935.0,2837.5,2878.5,2940.5,2950.0,2950.0,3000.0,3100.0,3125.0,24.180409
59,59,11379,New York,NY,"New York, NY",Queens,635,NaN,NaN,NaN,...,1975.0,2000.0,2000.0,2200.0,2150.0,2000.0,2000.0,2000.0,2100.0,NaN
60,60,10037,New York,NY,"New York, NY",New York,664,NaN,NaN,NaN,...,1599.5,1655.0,1650.0,1630.0,1650.0,1680.0,1682.0,1700.0,1695.0,NaN
61,61,11361,New York,NY,"New York, NY",Queens,712,NaN,NaN,NaN,...,2200.0,2199.5,2200.0,2200.0,2200.0,2199.5,2200.0,2400.0,2300.0,NaN
62,62,11378,New York,NY,"New York, NY",Queens,726,NaN,NaN,NaN,...,1925.0,2100.0,2100.0,2150.0,2200.0,2150.0,2100.0,2100.0,2125.0,NaN
63,63,11360,New York,NY,"New York, NY",Queens,745,NaN,NaN,NaN,...,2350.0,2350.0,2350.0,2300.0,2250.0,2300.0,2350.0,2350.0,2350.0,NaN
64,64,11356,New York,NY,"New York, NY",Queens,808,NaN,NaN,NaN,...,2000.0,1975.0,2100.0,2200.0,2200.0,2195.0,2200.0,2300.0,2200.0,NaN
65,65,10005,New York,NY,"New York, NY",New York,825,2695.0,2599.0,2600.0,...,3104.0,3150.0,3207.0,3137.0,3087.0,3190.0,3250.0,3253.0,3302.0,22.523191
66,66,10018,New York,NY,"New York, NY",New York,826,NaN,2313.5,2200.0,...,2752.5,2755.0,2755.0,2807.5,2850.0,2755.0,2865.0,2852.5,2970.0,NaN
67,67,10280,New York,NY,"New York, NY",New York,833,2750.0,2800.0,2795.0,...,3220.0,3400.0,3400.0,3300.0,3325.0,3400.0,3400.0,3390.0,3500.0,27.272727
68,68,11109,New York,NY,"New York, NY",Queens,838,NaN,NaN,NaN,...,2237.5,2260.0,2300.0,2340.0,2330.0,2340.0,2340.0,2342.5,2400.0,NaN
69,69,10069,New York,NY,"New York, NY",New York,843,3050.0,2885.0,2855.0,...,3075.0,3125.0,3288.0,3288.0,3160.0,3220.0,3467.5,3500.0,3400.0,11.475410
70,70,10006,New York,NY,"New York, NY",New York,849,2500.0,2445.5,2445.0,...,2912.5,2845.0,3041.0,3000.0,3047.0,3092.5,2965.0,3032.5,2982.5,19.300000
71,71,10004,New York,NY,"New York, NY",New York,850,NaN,NaN,NaN,...,3500.0,3595.0,3375.0,2987.0,2850.0,3350.0,3250.0,3050.0,3138.0,NaN

In [8]:
df1 = df.drop('Unnamed: 0', 1)
df1

,RegionName,City,State,Metro,CountyName,SizeRank,2011-11,2011-12,2012-01,2012-02,...,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,%_increase
0,10025,New York,NY,"New York, NY",New York,1,1900.0,1900.0,1895.0,1900.0,...,2618.0,2600.0,2600.0,2695.0,2625.0,2650.0,2700.0,2659.5,2450.0,28.947368
1,10023,New York,NY,"New York, NY",New York,3,2295.0,2200.0,2292.5,2295.0,...,2800.0,2893.0,2900.0,2800.0,2800.0,2850.0,2800.0,2770.0,2695.0,17.429194
2,10002,New York,NY,"New York, NY",New York,6,NaN,NaN,NaN,NaN,...,2400.0,2272.5,2199.0,2199.5,2227.5,2500.0,2500.0,2295.0,2312.5,NaN
3,11226,New York,NY,"New York, NY",Kings,10,NaN,NaN,NaN,NaN,...,1500.0,1597.0,1550.0,1525.0,1525.0,1550.0,1550.0,1645.0,1600.0,NaN
4,11375,New York,NY,"New York, NY",Queens,11,1325.0,1300.0,1300.0,1325.0,...,1695.0,1690.0,1725.0,1800.0,1800.0,1795.0,1785.0,1695.0,1925.0,45.283019
5,10016,New York,NY,"New York, NY",New York,12,2300.0,2275.0,2299.5,2300.0,...,2695.0,2750.0,2750.0,2787.5,2795.0,2800.0,2775.0,2775.0,2750.0,19.565217
6,11235,New York,NY,"New York, NY",Kings,13,NaN,NaN,NaN,NaN,...,1700.0,1695.0,1550.0,1650.0,1699.5,1700.0,1632.5,1695.0,1725.0,NaN
7,10009,New York,NY,"New York, NY",New York,14,1900.0,1900.0,1925.0,1925.0,...,2100.0,2100.0,2100.0,2136.0,2150.0,2199.0,2195.0,2150.0,2200.0,15.789474
8,10029,New York,NY,"New York, NY",New York,15,NaN,NaN,NaN,NaN,...,2800.0,2750.0,2775.0,2800.0,2750.0,2800.0,2812.5,2800.0,2750.0,NaN
9,10128,New York,NY,"New York, NY",New York,16,1950.0,1900.0,1875.0,1862.5,...,2250.0,2249.0,2150.0,2175.0,2200.0,2179.0,2150.0,2150.0,2137.5,9.615385
10,10011,New York,NY,"New York, NY",New York,17,2500.0,2500.0,2490.0,2495.0,...,2860.0,2850.0,2850.0,2895.0,2900.0,2900.0,2950.0,2950.0,2950.0,18.000000
11,10003,New York,NY,"New York, NY",New York,22,2495.0,2350.0,2375.0,2495.0,...,2675.0,2700.0,2725.0,2800.0,2800.0,2700.0,2800.0,2750.0,2695.0,8.016032
12,11209,New York,NY,"New York, NY",Kings,30,NaN,1100.0,1100.0,1175.0,...,1450.0,1650.0,1605.0,1575.0,1497.5,1672.5,1695.0,1750.0,1725.0,NaN
13,11201,New York,NY,"New York, NY",Kings,31,NaN,NaN,2200.0,2225.0,...,2500.0,2562.0,2542.0,2564.0,2543.0,2584.0,2666.0,2715.0,2704.0,NaN
14,10024,New York,NY,"New York, NY",New York,34,2095.0,2100.0,2025.0,2050.0,...,2397.5,2330.0,2350.0,2395.0,2400.0,2450.0,2400.0,2437.5,2397.5,14.439141
15,11214,New York,NY,"New York, NY",Kings,37,NaN,NaN,NaN,NaN,...,1750.0,1750.0,1787.5,1875.0,1900.0,2000.0,2000.0,1950.0,1800.0,NaN
16,11234,New York,NY,"New York, NY",Kings,43,NaN,NaN,NaN,NaN,...,1800.0,2050.0,2000.0,2000.0,2000.0,2250.0,2000.0,2000.0,1950.0,NaN
17,10019,New York,NY,"New York, NY",New York,44,2500.0,2497.5,2500.0,2540.0,...,2900.0,2880.0,2900.0,2925.0,2900.5,3000.0,2995.0,3000.0,3010.0,20.400000
18,11355,New York,NY,"New York, NY",Queens,48,1253.0,1350.0,1300.0,1367.0,...,1700.0,1725.0,1700.0,1700.0,1950.0,2100.0,2050.0,1950.0,1900.0,51.636073
19,11215,New York,NY,"New York, NY",Kings,52,NaN,NaN,NaN,NaN,...,2300.0,2500.0,2369.0,2300.0,2250.0,2200.0,2225.0,2200.0,2400.0,NaN
20,11221,New York,NY,"New York, NY",Kings,53,1435.0,1450.0,1350.0,1450.0,...,1950.0,2000.0,1800.0,1800.0,1850.0,2000.0,2175.0,1999.5,2000.0,39.372822
21,11211,New York,NY,"New York, NY",Kings,60,2250.0,2400.0,2600.0,2224.5,...,2830.0,2745.0,2745.0,2710.0,2750.0,2750.0,2692.5,2750.0,2790.0,24.000000
22,11373,New York,NY,"New York, NY",Queens,61,1195.0,1195.0,1225.0,1225.0,...,1472.5,1550.0,1650.0,1605.0,1512.0,1475.0,1500.0,1581.0,1600.0,33.891213
23,11385,New York,NY,"New York, NY",Queens,61,NaN,NaN,NaN,NaN,...,2150.0,2300.0,2000.0,2075.0,2000.0,2000.0,2000.0,2050.0,2100.0,NaN
24,10028,New York,NY,"New York, NY",New York,66,1895.0,1875.0,1865.0,1850.0,...,1995.0,2063.0,2095.0,2100.0,2095.0,2150.0,2125.0,2100.0,2100.0,10.817942
25,10027,New York,NY,"New York, NY",New York,75,NaN,NaN,NaN,NaN,...,2025.0,2100.0,2250.0,2147.5,2015.5,1950.0,1895.0,2025.0,2045.5,NaN
26,10021,New York,NY,"New York, NY",New York,86,1900.0,1900.0,1895.0,1895.0,...,2177.5,2104.0,2150.0,2150.0,2195.0,2250.0,2225.0,2200.0,2100.0,10.526316
27,11208,New York,NY,"New York, NY",Kings,96,NaN,NaN,NaN,NaN,...,2100.0,2100.0,2100.0,2100.0,2175.0,2125.0,2124.5,2325.0,2200.0,NaN
28,11204,New York,NY,"New York, NY",Kings,106,NaN,NaN,NaN,NaN,...,1775.0,1975.0,1800.0,1800.0,1600.0,1600.0,1775.0,1800.0,1950.0,NaN
29,10032,New York,NY,"New York, NY",New York,108,NaN,NaN,NaN,NaN,...,1527.5,1595.0,1595.0,1557.0,1620.0,1645.0,1645.0,1600.0,1600.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,10065,New York,NY,"New York, NY",New York,313,2495.0,2337.5,2295.0,2350.0,...,2730.0,2695.0,2795.0,2700.0,2700.0,2762.5,2850.0,2800.0,2625.0,5.210421
43,11435,New York,NY,"New York, NY",Queens,338,NaN,NaN,NaN,NaN,...,1475.0,1475.0,1499.0,1599.5,1675.0,1695.0,1600.0,1612.5,1599.5,NaN
44,11205,New York,NY,"New York, NY",Kings,357,NaN,NaN,NaN,NaN,...,2350.0,2380.0,2261.0,2261.0,2352.0,2397.5,2395.0,2397.5,2400.0,NaN
45,11217,New York,NY,"New York, NY",Kings,399,NaN,NaN,NaN,NaN,...,2535.0,2431.5,2340.0,2350.0,2580.0,2655.0,2745.0,2723.0,2710.0,NaN
46,11365,New York,NY,"New York, NY",Queens,401,NaN,NaN,NaN,NaN,...,2400.0,2300.0,2300.0,2297.5,2200.0,2300.0,2375.0,2450.0,2500.0,NaN
47,10035,New York,NY,"New York, NY",New York,428,1787.0,1742.5,1650.0,1650.0,...,1850.0,1743.5,1855.0,1795.0,1772.5,1850.0,1795.0,1922.5,1885.0,5.484051
48,10075,New York,NY,"New York, NY",New York,433,1775.0,1775.0,1750.0,1795.0,...,2000.0,1950.0,1973.5,1997.0,1995.0,2000.0,2075.0,2075.0,2050.0,15.492958
49,11102,New York,NY,"New York, NY",Queens,434,NaN,NaN,NaN,NaN,...,2000.0,2050.0,2000.0,2000.0,1932.0,1995.0,1837.5,2100.0,2100.0,NaN
50,11101,New York,NY,"New York, NY",Queens,439,NaN,NaN,NaN,NaN,...,2235.0,2251.0,2238.5,2271.0,2315.0,2347.5,2416.0,2418.0,2400.0,NaN
51,10001,New York,NY,"New York, NY",New York,466,NaN,NaN,NaN,2455.0,...,2987.5,3037.0,2995.5,2907.0,2999.5,3177.0,3080.0,3077.0,3074.5,NaN
52,10012,New York,NY,"New York, NY",New York,472,NaN,NaN,2350.0,2395.0,...,2750.0,2750.0,2800.0,2892.5,2895.0,3000.0,2890.0,2882.5,2870.0,NaN
53,11249,New York,NY,"New York, NY",Kings,488,NaN,NaN,NaN,NaN,...,2865.0,2995.0,2995.0,2939.5,2950.0,2953.0,2950.0,3193.0,3200.0,NaN
54,11357,New York,NY,"New York, NY",Queens,512,NaN,NaN,NaN,NaN,...,2300.0,2200.0,2200.0,2200.0,2200.0,2225.0,2300.0,2300.0,2300.0,NaN
55,11358,New York,NY,"New York, NY",Queens,580,NaN,NaN,NaN,NaN,...,2200.0,2200.0,2200.0,2100.0,2147.5,2300.0,2300.0,2300.0,2300.0,NaN
56,10030,New York,NY,"New York, NY",New York,583,NaN,NaN,NaN,NaN,...,1537.5,1627.5,1550.0,1550.0,1625.0,1600.0,1695.0,1600.0,1595.0,NaN
57,10017,New York,NY,"New York, NY",New York,617,2300.0,2200.0,2200.0,2275.0,...,2497.0,2500.0,2550.0,2580.0,2575.0,2580.0,2600.0,2650.0,2600.0,13.043478
58,10038,New York,NY,"New York, NY",New York,630,2516.5,2550.0,2550.0,2545.0,...,2935.0,2837.5,2878.5,2940.5,2950.0,2950.0,3000.0,3100.0,3125.0,24.180409
59,11379,New York,NY,"New York, NY",Queens,635,NaN,NaN,NaN,NaN,...,1975.0,2000.0,2000.0,2200.0,2150.0,2000.0,2000.0,2000.0,2100.0,NaN
60,10037,New York,NY,"New York, NY",New York,664,NaN,NaN,NaN,NaN,...,1599.5,1655.0,1650.0,1630.0,1650.0,1680.0,1682.0,1700.0,1695.0,NaN
61,11361,New York,NY,"New York, NY",Queens,712,NaN,NaN,NaN,NaN,...,2200.0,2199.5,2200.0,2200.0,2200.0,2199.5,2200.0,2400.0,2300.0,NaN
62,11378,New York,NY,"New York, NY",Queens,726,NaN,NaN,NaN,NaN,...,1925.0,2100.0,2100.0,2150.0,2200.0,2150.0,2100.0,2100.0,2125.0,NaN
63,11360,New York,NY,"New York, NY",Queens,745,NaN,NaN,NaN,NaN,...,2350.0,2350.0,2350.0,2300.0,2250.0,2300.0,2350.0,2350.0,2350.0,NaN
64,11356,New York,NY,"New York, NY",Queens,808,NaN,NaN,NaN,NaN,...,2000.0,1975.0,2100.0,2200.0,2200.0,2195.0,2200.0,2300.0,2200.0,NaN
65,10005,New York,NY,"New York, NY",New York,825,2695.0,2599.0,2600.0,2600.0,...,3104.0,3150.0,3207.0,3137.0,3087.0,3190.0,3250.0,3253.0,3302.0,22.523191
66,10018,New York,NY,"New York, NY",New York,826,NaN,2313.5,2200.0,2415.0,...,2752.5,2755.0,2755.0,2807.5,2850.0,2755.0,2865.0,2852.5,2970.0,NaN
67,10280,New York,NY,"New York, NY",New York,833,2750.0,2800.0,2795.0,2700.0,...,3220.0,3400.0,3400.0,3300.0,3325.0,3400.0,3400.0,3390.0,3500.0,27.272727
68,11109,New York,NY,"New York, NY",Queens,838,NaN,NaN,NaN,NaN,...,2237.5,2260.0,2300.0,2340.0,2330.0,2340.0,2340.0,2342.5,2400.0,NaN
69,10069,New York,NY,"New York, NY",New York,843,3050.0,2885.0,2855.0,2800.0,...,3075.0,3125.0,3288.0,3288.0,3160.0,3220.0,3467.5,3500.0,3400.0,11.475410
70,10006,New York,NY,"New York, NY",New York,849,2500.0,2445.5,2445.0,2499.5,...,2912.5,2845.0,3041.0,3000.0,3047.0,3092.5,2965.0,3032.5,2982.5,19.300000
71,10004,New York,NY,"New York, NY",New York,850,NaN,NaN,NaN,NaN,...,3500.0,3595.0,3375.0,2987.0,2850.0,3350.0,3250.0,3050.0,3138.0,NaN

In [17]:
df1.index.name = 'Id'
df1

,RegionName,City,State,Metro,CountyName,SizeRank,2011-11,2011-12,2012-01,2012-02,...,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,%_increase
Id,,,,,,,,,,,,,,,,,,,,,
0,10025,New York,NY,"New York, NY",New York,1,1900.0,1900.0,1895.0,1900.0,...,2618.0,2600.0,2600.0,2695.0,2625.0,2650.0,2700.0,2659.5,2450.0,28.947368
1,10023,New York,NY,"New York, NY",New York,3,2295.0,2200.0,2292.5,2295.0,...,2800.0,2893.0,2900.0,2800.0,2800.0,2850.0,2800.0,2770.0,2695.0,17.429194
2,10002,New York,NY,"New York, NY",New York,6,NaN,NaN,NaN,NaN,...,2400.0,2272.5,2199.0,2199.5,2227.5,2500.0,2500.0,2295.0,2312.5,NaN
3,11226,New York,NY,"New York, NY",Kings,10,NaN,NaN,NaN,NaN,...,1500.0,1597.0,1550.0,1525.0,1525.0,1550.0,1550.0,1645.0,1600.0,NaN
4,11375,New York,NY,"New York, NY",Queens,11,1325.0,1300.0,1300.0,1325.0,...,1695.0,1690.0,1725.0,1800.0,1800.0,1795.0,1785.0,1695.0,1925.0,45.283019
5,10016,New York,NY,"New York, NY",New York,12,2300.0,2275.0,2299.5,2300.0,...,2695.0,2750.0,2750.0,2787.5,2795.0,2800.0,2775.0,2775.0,2750.0,19.565217
6,11235,New York,NY,"New York, NY",Kings,13,NaN,NaN,NaN,NaN,...,1700.0,1695.0,1550.0,1650.0,1699.5,1700.0,1632.5,1695.0,1725.0,NaN
7,10009,New York,NY,"New York, NY",New York,14,1900.0,1900.0,1925.0,1925.0,...,2100.0,2100.0,2100.0,2136.0,2150.0,2199.0,2195.0,2150.0,2200.0,15.789474
8,10029,New York,NY,"New York, NY",New York,15,NaN,NaN,NaN,NaN,...,2800.0,2750.0,2775.0,2800.0,2750.0,2800.0,2812.5,2800.0,2750.0,NaN
9,10128,New York,NY,"New York, NY",New York,16,1950.0,1900.0,1875.0,1862.5,...,2250.0,2249.0,2150.0,2175.0,2200.0,2179.0,2150.0,2150.0,2137.5,9.615385
10,10011,New York,NY,"New York, NY",New York,17,2500.0,2500.0,2490.0,2495.0,...,2860.0,2850.0,2850.0,2895.0,2900.0,2900.0,2950.0,2950.0,2950.0,18.000000
11,10003,New York,NY,"New York, NY",New York,22,2495.0,2350.0,2375.0,2495.0,...,2675.0,2700.0,2725.0,2800.0,2800.0,2700.0,2800.0,2750.0,2695.0,8.016032
12,11209,New York,NY,"New York, NY",Kings,30,NaN,1100.0,1100.0,1175.0,...,1450.0,1650.0,1605.0,1575.0,1497.5,1672.5,1695.0,1750.0,1725.0,NaN
13,11201,New York,NY,"New York, NY",Kings,31,NaN,NaN,2200.0,2225.0,...,2500.0,2562.0,2542.0,2564.0,2543.0,2584.0,2666.0,2715.0,2704.0,NaN
14,10024,New York,NY,"New York, NY",New York,34,2095.0,2100.0,2025.0,2050.0,...,2397.5,2330.0,2350.0,2395.0,2400.0,2450.0,2400.0,2437.5,2397.5,14.439141
15,11214,New York,NY,"New York, NY",Kings,37,NaN,NaN,NaN,NaN,...,1750.0,1750.0,1787.5,1875.0,1900.0,2000.0,2000.0,1950.0,1800.0,NaN
16,11234,New York,NY,"New York, NY",Kings,43,NaN,NaN,NaN,NaN,...,1800.0,2050.0,2000.0,2000.0,2000.0,2250.0,2000.0,2000.0,1950.0,NaN
17,10019,New York,NY,"New York, NY",New York,44,2500.0,2497.5,2500.0,2540.0,...,2900.0,2880.0,2900.0,2925.0,2900.5,3000.0,2995.0,3000.0,3010.0,20.400000
18,11355,New York,NY,"New York, NY",Queens,48,1253.0,1350.0,1300.0,1367.0,...,1700.0,1725.0,1700.0,1700.0,1950.0,2100.0,2050.0,1950.0,1900.0,51.636073
19,11215,New York,NY,"New York, NY",Kings,52,NaN,NaN,NaN,NaN,...,2300.0,2500.0,2369.0,2300.0,2250.0,2200.0,2225.0,2200.0,2400.0,NaN
20,11221,New York,NY,"New York, NY",Kings,53,1435.0,1450.0,1350.0,1450.0,...,1950.0,2000.0,1800.0,1800.0,1850.0,2000.0,2175.0,1999.5,2000.0,39.372822
21,11211,New York,NY,"New York, NY",Kings,60,2250.0,2400.0,2600.0,2224.5,...,2830.0,2745.0,2745.0,2710.0,2750.0,2750.0,2692.5,2750.0,2790.0,24.000000
22,11373,New York,NY,"New York, NY",Queens,61,1195.0,1195.0,1225.0,1225.0,...,1472.5,1550.0,1650.0,1605.0,1512.0,1475.0,1500.0,1581.0,1600.0,33.891213
23,11385,New York,NY,"New York, NY",Queens,61,NaN,NaN,NaN,NaN,...,2150.0,2300.0,2000.0,2075.0,2000.0,2000.0,2000.0,2050.0,2100.0,NaN
24,10028,New York,NY,"New York, NY",New York,66,1895.0,1875.0,1865.0,1850.0,...,1995.0,2063.0,2095.0,2100.0,2095.0,2150.0,2125.0,2100.0,2100.0,10.817942
25,10027,New York,NY,"New York, NY",New York,75,NaN,NaN,NaN,NaN,...,2025.0,2100.0,2250.0,2147.5,2015.5,1950.0,1895.0,2025.0,2045.5,NaN
26,10021,New York,NY,"New York, NY",New York,86,1900.0,1900.0,1895.0,1895.0,...,2177.5,2104.0,2150.0,2150.0,2195.0,2250.0,2225.0,2200.0,2100.0,10.526316
27,11208,New York,NY,"New York, NY",Kings,96,NaN,NaN,NaN,NaN,...,2100.0,2100.0,2100.0,2100.0,2175.0,2125.0,2124.5,2325.0,2200.0,NaN
28,11204,New York,NY,"New York, NY",Kings,106,NaN,NaN,NaN,NaN,...,1775.0,1975.0,1800.0,1800.0,1600.0,1600.0,1775.0,1800.0,1950.0,NaN
29,10032,New York,NY,"New York, NY",New York,108,NaN,NaN,NaN,NaN,...,1527.5,1595.0,1595.0,1557.0,1620.0,1645.0,1645.0,1600.0,1600.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,10065,New York,NY,"New York, NY",New York,313,2495.0,2337.5,2295.0,2350.0,...,2730.0,2695.0,2795.0,2700.0,2700.0,2762.5,2850.0,2800.0,2625.0,5.210421
43,11435,New York,NY,"New York, NY",Queens,338,NaN,NaN,NaN,NaN,...,1475.0,1475.0,1499.0,1599.5,1675.0,1695.0,1600.0,1612.5,1599.5,NaN
44,11205,New York,NY,"New York, NY",Kings,357,NaN,NaN,NaN,NaN,...,2350.0,2380.0,2261.0,2261.0,2352.0,2397.5,2395.0,2397.5,2400.0,NaN
45,11217,New York,NY,"New York, NY",Kings,399,NaN,NaN,NaN,NaN,...,2535.0,2431.5,2340.0,2350.0,2580.0,2655.0,2745.0,2723.0,2710.0,NaN
46,11365,New York,NY,"New York, NY",Queens,401,NaN,NaN,NaN,NaN,...,2400.0,2300.0,2300.0,2297.5,2200.0,2300.0,2375.0,2450.0,2500.0,NaN
47,10035,New York,NY,"New York, NY",New York,428,1787.0,1742.5,1650.0,1650.0,...,1850.0,1743.5,1855.0,1795.0,1772.5,1850.0,1795.0,1922.5,1885.0,5.484051
48,10075,New York,NY,"New York, NY",New York,433,1775.0,1775.0,1750.0,1795.0,...,2000.0,1950.0,1973.5,1997.0,1995.0,2000.0,2075.0,2075.0,2050.0,15.492958
49,11102,New York,NY,"New York, NY",Queens,434,NaN,NaN,NaN,NaN,...,2000.0,2050.0,2000.0,2000.0,1932.0,1995.0,1837.5,2100.0,2100.0,NaN
50,11101,New York,NY,"New York, NY",Queens,439,NaN,NaN,NaN,NaN,...,2235.0,2251.0,2238.5,2271.0,2315.0,2347.5,2416.0,2418.0,2400.0,NaN
51,10001,New York,NY,"New York, NY",New York,466,NaN,NaN,NaN,2455.0,...,2987.5,3037.0,2995.5,2907.0,2999.5,3177.0,3080.0,3077.0,3074.5,NaN
52,10012,New York,NY,"New York, NY",New York,472,NaN,NaN,2350.0,2395.0,...,2750.0,2750.0,2800.0,2892.5,2895.0,3000.0,2890.0,2882.5,2870.0,NaN
53,11249,New York,NY,"New York, NY",Kings,488,NaN,NaN,NaN,NaN,...,2865.0,2995.0,2995.0,2939.5,2950.0,2953.0,2950.0,3193.0,3200.0,NaN
54,11357,New York,NY,"New York, NY",Queens,512,NaN,NaN,NaN,NaN,...,2300.0,2200.0,2200.0,2200.0,2200.0,2225.0,2300.0,2300.0,2300.0,NaN
55,11358,New York,NY,"New York, NY",Queens,580,NaN,NaN,NaN,NaN,...,2200.0,2200.0,2200.0,2100.0,2147.5,2300.0,2300.0,2300.0,2300.0,NaN
56,10030,New York,NY,"New York, NY",New York,583,NaN,NaN,NaN,NaN,...,1537.5,1627.5,1550.0,1550.0,1625.0,1600.0,1695.0,1600.0,1595.0,NaN
57,10017,New York,NY,"New York, NY",New York,617,2300.0,2200.0,2200.0,2275.0,...,2497.0,2500.0,2550.0,2580.0,2575.0,2580.0,2600.0,2650.0,2600.0,13.043478
58,10038,New York,NY,"New York, NY",New York,630,2516.5,2550.0,2550.0,2545.0,...,2935.0,2837.5,2878.5,2940.5,2950.0,2950.0,3000.0,3100.0,3125.0,24.180409
59,11379,New York,NY,"New York, NY",Queens,635,NaN,NaN,NaN,NaN,...,1975.0,2000.0,2000.0,2200.0,2150.0,2000.0,2000.0,2000.0,2100.0,NaN
60,10037,New York,NY,"New York, NY",New York,664,NaN,NaN,NaN,NaN,...,1599.5,1655.0,1650.0,1630.0,1650.0,1680.0,1682.0,1700.0,1695.0,NaN
61,11361,New York,NY,"New York, NY",Queens,712,NaN,NaN,NaN,NaN,...,2200.0,2199.5,2200.0,2200.0,2200.0,2199.5,2200.0,2400.0,2300.0,NaN
62,11378,New York,NY,"New York, NY",Queens,726,NaN,NaN,NaN,NaN,...,1925.0,2100.0,2100.0,2150.0,2200.0,2150.0,2100.0,2100.0,2125.0,NaN
63,11360,New York,NY,"New York, NY",Queens,745,NaN,NaN,NaN,NaN,...,2350.0,2350.0,2350.0,2300.0,2250.0,2300.0,2350.0,2350.0,2350.0,NaN
64,11356,New York,NY,"New York, NY",Queens,808,NaN,NaN,NaN,NaN,...,2000.0,1975.0,2100.0,2200.0,2200.0,2195.0,2200.0,2300.0,2200.0,NaN
65,10005,New York,NY,"New York, NY",New York,825,2695.0,2599.0,2600.0,2600.0,...,3104.0,3150.0,3207.0,3137.0,3087.0,3190.0,3250.0,3253.0,3302.0,22.523191
66,10018,New York,NY,"New York, NY",New York,826,NaN,2313.5,2200.0,2415.0,...,2752.5,2755.0,2755.0,2807.5,2850.0,2755.0,2865.0,2852.5,2970.0,NaN
67,10280,New York,NY,"New York, NY",New York,833,2750.0,2800.0,2795.0,2700.0,...,3220.0,3400.0,3400.0,3300.0,3325.0,3400.0,3400.0,3390.0,3500.0,27.272727
68,11109,New York,NY,"New York, NY",Queens,838,NaN,NaN,NaN,NaN,...,2237.5,2260.0,2300.0,2340.0,2330.0,2340.0,2340.0,2342.5,2400.0,NaN
69,10069,New York,NY,"New York, NY",New York,843,3050.0,2885.0,2855.0,2800.0,...,3075.0,3125.0,3288.0,3288.0,3160.0,3220.0,3467.5,3500.0,3400.0,11.475410
70,10006,New York,NY,"New York, NY",New York,849,2500.0,2445.5,2445.0,2499.5,...,2912.5,2845.0,3041.0,3000.0,3047.0,3092.5,2965.0,3032.5,2982.5,19.300000
71,10004,New York,NY,"New York, NY",New York,850,NaN,NaN,NaN,NaN,...,3500.0,3595.0,3375.0,2987.0,2850.0,3350.0,3250.0,3050.0,3138.0,NaN

In [18]:
# len(df1['RegionName'].unique()) ##72 zip codes
# len(df1['City'].unique()) # 1- Only zipcodes in the new york city
# len(df1['Metro'].unique()) #1
# len(df1['CountyName'].unique()) # 3
# df1['CountyName'].unique() # ['New York', 'Kings', 'Queens']
# len(df1['SizeRank'].unique()) #71

71

In [22]:
df_harlem=pd.read_csv("C:/Users/Ayushee/Dropbox/Columbia/Spring 2019/Business Analytics/Group Project/gentrification_yelp-master/gentrification_yelp-master/east_harlem_one_hot_category.csv")
print(df_harlem)

    oldest_review  category_african  category_bagels  category_bakeries  \
0         2005-08                 0                0                  0
1         2005-10                 0                0                  0
2         2005-12                 0                0                  0
3         2006-01                 0                0                  0
4         2006-03                 0                0                  0
5         2006-04                 0                0                  0
6         2006-05                 0                0                  0
7         2006-07                 0                0                  0
8         2006-08                 0                0                  0
9         2006-09                 0                0                  0
10        2006-11                 0                0                  0
11        2006-12                 0                0                  0
12        2007-01                 0                0                  0
13        2007-02                 0                0                  0
14        2007-03                 0                0                  1
15        2007-04                 0                0                  0
16        2007-06                 0                0                  0
17        2007-10                 0                0                  0
18        2007-12                 0                0                  0
19        2008-01                 0                0                  0
20        2008-02                 0                0                  0
21        2008-03                 0                0                  0
22        2008-04                 0                0                  1
23        2008-05                 0                0                  0
24        2008-06                 0                0                  0
25        2008-07                 0                0                  0
26        2008-08                 0                0                  0
27        2008-09                 0                0                  0
28        2008-10                 0                0                  0
29        2008-12                 0                0                  0
..            ...               ...              ...                ...
113       2016-04                 0                0                  0
114       2016-05                 0                0                  1
115       2016-06                 0                0                  0
116       2016-07                 0                1                  0
117       2016-08                 0                0                  1
118       2016-09                 0                0                  0
119       2016-10                 0                0                  0
120       2016-11                 0                0                  0
121       2016-12                 0                0                  0
122       2017-01                 0                0                  0
123       2017-02                 0                0                  0
124       2017-03                 0                0                  0
125       2017-04                 0                0                  0
126       2017-05                 0                0                  0
127       2017-06                 0                1                  0
128       2017-07                 0                0                  0
129       2017-08                 0                0                  0
130       2017-09                 0                0                  0
131       2017-10                 0                0                  0
132       2017-11                 0                0                  0
133       2017-12                 0                0                  0
134       2018-01                 1                0                  0
135       2018-02                 0                0                  1
136       2018-03                 0                0                  0
137       2018-04                 0                0                  0
138       2018-05                 0                0                  1
139       2018-06                 0                0                  0
140       2018-07                 0                0                  0
141       2018-08                 0                0                  1
142       2018-09                 0                0                  1

     category_bars  category_bbq  category_beerbar  category_breakfast_brunch  \
0                0             0                 0                          0
1                0             0                 0                          0
2                0             0                 0                          0
3                0             0                 0                          0
4                0             0                 0                          0
5                0             0                 0                          0
6                0             0                 0                          0
7                0             0                 0                          0
8                0             0                 0                          0
9                1             0                 0                          0
10               0             0                 0                          0
11               0             0                 0                          0
12               0             0                 0                          0
13               0             0                 0                          0
14               0             0                 0                          0
15               0             0                 0                          0
16               0             0                 0                          0
17               0             0                 0                          0
18               0             0                 0                          0
19               0             0                 0                          0
20               0             0                 0                          0
21               0             0                 0                          0
22               0             0                 0                          0
23               0             0                 0                          0
24               0             0                 0                          0
25               0             0                 0                          0
26               0             0                 0                          0
27               0             0                 0                          1
28               0             0                 0                          0
29               0             0                 0                          0
..             ...           ...               ...                        ...
113              0             0                 0                          0
114              0             0                 0                          0
115              0             0                 0                          0
116              0             0                 0                          0
117              0             0                 1                          0
118              0             0                 0                          0
119              0             0                 0                          0
120              0             0                 0                          0
121              0             0                 0                          0
122              0             0                 0                          0
123              0             0                 0                          0
124              0             0                 0                          0
125              0             0                 0                          0
126              0             0                 0                          0
127              0             0                 0                          0
128              0             0                 1                          0
129              0             0                 0                          0
130              0             0                 0                          0
131              0             0                 1                          0
132              0             0                 0                          0
133              0             0                 0                          0
134              0             0                 0                          0
135              0             0                 0                          0
136              0             0                 0                          0
137              0             0                 0                          0
138              0             0                 0                          0
139              0             0                 0                          0
140              0             0                 0                          0
141              0             0                 0                          1
142              0             0                 0                          1

     category_bubbletea  category_buffets         ...          category_tacos  \
0                     0                 0         ...                       0
1                     0                 0         ...                       0
2                     0                 0         ...                       0
3                     0                 0         ...                       0
4                     0                 0         ...                       0
5                     0                 0         ...                       0
6                     0                 0         ...                       0
7                     0                 0         ...                       0
8                     0                 0         ...                       0
9                     0                 0         ...                       0
10                    0                 0         ...                       0
11                    0                 0         ...                       0
12                    0                 0         ...                       0
13                    0                 0         ...                       0
14                    0                 0         ...                       0
15                    0                 0         ...                       0
16                    0                 0         ...                       0
17                    0                 0         ...                       0
18                    0                 0         ...                       0
19                    0                 0         ...                       0
20                    0                 0         ...                       0
21                    0                 0         ...                       0
22                    0                 0         ...                       0
23                    0                 0         ...                       0
24                    0                 0         ...                       0
25                    0                 0         ...                       0
26                    0                 0         ...                       0
27                    0                 0         ...                       0
28                    0                 0         ...                       0
29                    0                 0         ...                       0
..                  ...               ...         ...                     ...
113                   0                 0         ...                       0
114                   0                 0         ...                       0
115                   0                 0         ...                       0
116                   0                 0         ...                       0
117                   0                 0         ...                       0
118                   0                 0         ...                       0
119                   0                 0         ...                       0
120                   0                 0         ...                       0
121                   0                 0         ...                       0
122                   0                 0         ...                       0
123                   1                 0         ...                       0
124                   0                 0         ...                       0
125                   0                 0         ...                       0
126                   0                 0         ...                       0
127                   0                 0         ...                       0
128                   0                 0         ...                       0
129                   0                 0         ...                       0
130                   0                 0         ...                       0
131                   0                 0         ...                       0
132                   0                 0         ...                       0
133                   0                 0         ...                       0
134                   0                 1         ...                       0
135                   0                 0         ...                       0
136                   0                 0         ...                       0
137                   0                 0         ...                       0
138                   0                 0         ...                       0
139                   0                 0         ...                       1
140                   0                 0         ...                       0
141                   0                 0         ...                       0
142                   0                 0         ...                       0

     category_tapas  category_tapasmallplates  category_tex-mex  \
0                 0                         0                 0
1                 0                         0                 0
2                 0                         0                 0
3                 0                         0                 0
4                 0                         0                 0
5                 0                         0                 0
6                 0                         0                 0
7                 0                         0                 0
8                 0                         0                 0
9                 0                         0                 0
10                0                         0                 0
11                0                         0                 0
12                0                         0                 0
13                0                         0                 0
14                0                         0                 0
15                0                         0                 0
16                0                         0                 0
17                0                         0                 0
18                0                         0                 0
19                0                         0                 0
20                0                         0                 0
21                0                         0                 0
22                0                         0                 0
23                0                         0                 0
24                0                         0                 0
25                0                         0                 0
26                0                         0                 0
27                0                         0                 0
28                0                         0                 0
29                0                         0                 0
..              ...                       ...               ...
113               0                         0                 1
114               0                         0                 0
115               0                         0                 0
116               0                         0                 0
117               0                         0                 0
118               0                         0                 0
119               0                         0                 0
120               0                         0                 0
121               0                         0                 0
122               0                         0                 0
123               0                         0                 0
124               0                         0                 0
125               0                         0                 0
126               0                         0                 0
127               0                         0                 0
128               0                         0                 0
129               0                         0                 0
130               0                         0                 0
131               0                         0                 0
132               0                         0                 0
133               0                         0                 0
134               0                         0                 0
135               0                         0                 0
136               0                         0                 0
137               0                         0                 0
138               0                         0                 0
139               0                         0                 0
140               0                         0                 0
141               0                         0                 0
142               0                         0                 0

     category_thai  category_tobaccoshops  category_tradamerican  \
0                0                      0                      0
1                0                      0                      0
2                0                      0                      0
3                0                      0                      2
4                0                      0                      0
5                0                      0                      0
6                0                      0                      0
7                0                      0                      0
8                0                      0                      0
9                0                      0                      0
10               0                      0                      0
11               0                      0                      0
12               0                      0                      0
13               0                      0                      0
14               0                      0                      0
15               0                      0                      0
16               0                      0                      0
17               0                      0                      0
18               0                      0                      0
19               0                      0                      0
20               0                      0                      0
21               0                      0                      0
22               0                      0                      0
23               0                      0                      0
24               0                      0                      0
25               0                      0                      0
26               0                      0                      0

In [21]:
len(df_harlem['oldest_review'].unique())

143

In [27]:
df_gent=pd.read_csv("C:/Users/Ayushee/Dropbox/Columbia/Spring 2019/Business Analytics/Group Project/gentrification_yelp-master/gentrification_yelp-master/WithGentrificationFlag.csv")
df_gent1 = df_gent.drop('Unnamed: 0', 1)
df_gent1.index.name = 'Id'
df_gent1

,RegionName,City,State,Metro,CountyName,SizeRank,2010-03,2010-04,2010-05,2010-06,...,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,gentrification_label
Id,,,,,,,,,,,,,,,,,,,,,
0,10025,New York,NY,"New York, NY",New York,1,NaN,NaN,NaN,NaN,...,2618.0,2600.0,2600.0,2695.0,2625.0,2650.0,2700.0,2659.5,2450.0,Higher-Income
1,10023,New York,NY,"New York, NY",New York,3,NaN,NaN,NaN,NaN,...,2800.0,2893.0,2900.0,2800.0,2800.0,2850.0,2800.0,2770.0,2695.0,Higher-Income
2,10002,New York,NY,"New York, NY",New York,6,NaN,NaN,NaN,NaN,...,2400.0,2272.5,2199.0,2199.5,2227.5,2500.0,2500.0,2295.0,2312.5,Gentrifying
3,10467,New York,NY,"New York, NY",Bronx,8,NaN,NaN,NaN,NaN,...,1275.0,1375.0,1450.0,1450.0,1425.0,1400.0,1362.5,1500.0,1500.0,Non-Gentrifying
4,11226,New York,NY,"New York, NY",Kings,10,NaN,NaN,NaN,NaN,...,1500.0,1597.0,1550.0,1525.0,1525.0,1550.0,1550.0,1645.0,1600.0,Higher-Income
5,11375,New York,NY,"New York, NY",Queens,11,NaN,NaN,NaN,NaN,...,1695.0,1690.0,1725.0,1800.0,1800.0,1795.0,1785.0,1695.0,1925.0,Higher-Income
6,10016,New York,NY,"New York, NY",New York,12,NaN,NaN,NaN,NaN,...,2695.0,2750.0,2750.0,2787.5,2795.0,2800.0,2775.0,2775.0,2750.0,Higher-Income
7,11235,New York,NY,"New York, NY",Kings,13,NaN,NaN,NaN,NaN,...,1700.0,1695.0,1550.0,1650.0,1699.5,1700.0,1632.5,1695.0,1725.0,Higher-Income
8,10009,New York,NY,"New York, NY",New York,14,NaN,NaN,NaN,NaN,...,2100.0,2100.0,2100.0,2136.0,2150.0,2199.0,2195.0,2150.0,2200.0,Gentrifying
9,10029,New York,NY,"New York, NY",New York,15,NaN,NaN,NaN,NaN,...,2800.0,2750.0,2775.0,2800.0,2750.0,2800.0,2812.5,2800.0,2750.0,Gentrifying
10,10128,New York,NY,"New York, NY",New York,16,NaN,NaN,NaN,NaN,...,2250.0,2249.0,2150.0,2175.0,2200.0,2179.0,2150.0,2150.0,2137.5,Higher-Income
11,10011,New York,NY,"New York, NY",New York,17,NaN,NaN,NaN,NaN,...,2860.0,2850.0,2850.0,2895.0,2900.0,2900.0,2950.0,2950.0,2950.0,Higher-Income
12,10003,New York,NY,"New York, NY",New York,22,NaN,NaN,NaN,NaN,...,2675.0,2700.0,2725.0,2800.0,2800.0,2700.0,2800.0,2750.0,2695.0,Gentrifying
13,10462,New York,NY,"New York, NY",Bronx,23,NaN,NaN,NaN,NaN,...,1399.0,1400.0,1435.0,1495.0,1500.0,1550.0,1500.0,1500.0,1500.0,Higher-Income
14,11209,New York,NY,"New York, NY",Kings,30,NaN,NaN,NaN,NaN,...,1450.0,1650.0,1605.0,1575.0,1497.5,1672.5,1695.0,1750.0,1725.0,Higher-Income
15,11201,New York,NY,"New York, NY",Kings,31,NaN,NaN,NaN,NaN,...,2500.0,2562.0,2542.0,2564.0,2543.0,2584.0,2666.0,2715.0,2704.0,Higher-Income
16,10024,New York,NY,"New York, NY",New York,34,NaN,NaN,NaN,NaN,...,2397.5,2330.0,2350.0,2395.0,2400.0,2450.0,2400.0,2437.5,2397.5,Higher-Income
17,11214,New York,NY,"New York, NY",Kings,37,NaN,NaN,NaN,NaN,...,1750.0,1750.0,1787.5,1875.0,1900.0,2000.0,2000.0,1950.0,1800.0,Higher-Income
18,10458,New York,NY,"New York, NY",Bronx,42,NaN,NaN,NaN,NaN,...,1325.0,1312.5,1350.0,1450.0,1400.0,1425.0,1350.0,1400.0,1395.0,Non-Gentrifying
19,11234,New York,NY,"New York, NY",Kings,43,NaN,NaN,NaN,NaN,...,1800.0,2050.0,2000.0,2000.0,2000.0,2250.0,2000.0,2000.0,1950.0,Higher-Income
20,10019,New York,NY,"New York, NY",New York,44,NaN,NaN,NaN,NaN,...,2900.0,2880.0,2900.0,2925.0,2900.5,3000.0,2995.0,3000.0,3010.0,Higher-Income
21,11355,New York,NY,"New York, NY",Queens,48,NaN,NaN,NaN,NaN,...,1700.0,1725.0,1700.0,1700.0,1950.0,2100.0,2050.0,1950.0,1900.0,Higher-Income
22,11215,New York,NY,"New York, NY",Kings,52,NaN,NaN,NaN,NaN,...,2300.0,2500.0,2369.0,2300.0,2250.0,2200.0,2225.0,2200.0,2400.0,Higher-Income
23,11221,New York,NY,"New York, NY",Kings,53,NaN,NaN,NaN,NaN,...,1950.0,2000.0,1800.0,1800.0,1850.0,2000.0,2175.0,1999.5,2000.0,Gentrifying
24,11211,New York,NY,"New York, NY",Kings,60,NaN,NaN,NaN,NaN,...,2830.0,2745.0,2745.0,2710.0,2750.0,2750.0,2692.5,2750.0,2790.0,Gentrifying
25,11373,New York,NY,"New York, NY",Queens,61,NaN,NaN,NaN,NaN,...,1472.5,1550.0,1650.0,1605.0,1512.0,1475.0,1500.0,1581.0,1600.0,Higher-Income
26,11385,New York,NY,"New York, NY",Queens,61,NaN,NaN,NaN,NaN,...,2150.0,2300.0,2000.0,2075.0,2000.0,2000.0,2000.0,2050.0,2100.0,Higher-Income
27,10468,New York,NY,"New York, NY",Bronx,65,NaN,NaN,NaN,NaN,...,1375.0,1412.5,1400.0,1375.0,1350.0,1375.0,1395.0,1395.0,1350.0,Non-Gentrifying
28,10028,New York,NY,"New York, NY",New York,66,NaN,NaN,NaN,NaN,...,1995.0,2063.0,2095.0,2100.0,2095.0,2150.0,2125.0,2100.0,2100.0,Higher-Income
29,10027,New York,NY,"New York, NY",New York,75,NaN,NaN,NaN,NaN,...,2025.0,2100.0,2250.0,2147.5,2015.5,1950.0,1895.0,2025.0,2045.5,Gentrifying
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,10065,New York,NY,"New York, NY",New York,313,NaN,NaN,NaN,NaN,...,2730.0,2695.0,2795.0,2700.0,2700.0,2762.5,2850.0,2800.0,2625.0,Higher-Income
50,11435,New York,NY,"New York, NY",Queens,338,NaN,NaN,NaN,NaN,...,1475.0,1475.0,1499.0,1599.5,1675.0,1695.0,1600.0,1612.5,1599.5,Higher-Income
51,11205,New York,NY,"New York, NY",Kings,357,NaN,NaN,NaN,NaN,...,2350.0,2380.0,2261.0,2261.0,2352.0,2397.5,2395.0,2397.5,2400.0,Higher-Income
52,11217,New York,NY,"New York, NY",Kings,399,NaN,NaN,NaN,NaN,...,2535.0,2431.5,2340.0,2350.0,2580.0,2655.0,2745.0,2723.0,2710.0,Higher-Income
53,11365,New York,NY,"New York, NY",Queens,401,NaN,NaN,NaN,NaN,...,2400.0,2300.0,2300.0,2297.5,2200.0,2300.0,2375.0,2450.0,2500.0,Higher-Income
54,10035,New York,NY,"New York, NY",New York,428,NaN,NaN,NaN,NaN,...,1850.0,1743.5,1855.0,1795.0,1772.5,1850.0,1795.0,1922.5,1885.0,Gentrifying
55,10075,New York,NY,"New York, NY",New York,433,NaN,NaN,NaN,NaN,...,2000.0,1950.0,1973.5,1997.0,1995.0,2000.0,2075.0,2075.0,2050.0,Higher-Income
56,11102,New York,NY,"New York, NY",Queens,434,NaN,NaN,NaN,NaN,...,2000.0,2050.0,2000.0,2000.0,1932.0,1995.0,1837.5,2100.0,2100.0,Gentrifying
57,11101,New York,NY,"New York, NY",Queens,439,NaN,NaN,NaN,NaN,...,2235.0,2251.0,2238.5,2271.0,2315.0,2347.5,2416.0,2418.0,2400.0,Higher-Income
58,10001,New York,NY,"New York, NY",New York,466,NaN,NaN,NaN,NaN,...,2987.5,3037.0,2995.5,2907.0,2999.5,3177.0,3080.0,3077.0,3074.5,Higher-Income
59,10012,New York,NY,"New York, NY",New York,472,NaN,NaN,NaN,NaN,...,2750.0,2750.0,2800.0,2892.5,2895.0,3000.0,2890.0,2882.5,2870.0,Higher-Income
60,11249,New York,NY,"New York, NY",Kings,488,NaN,NaN,NaN,NaN,...,2865.0,2995.0,2995.0,2939.5,2950.0,2953.0,2950.0,3193.0,3200.0,Gentrifying
61,11357,New York,NY,"New York, NY",Queens,512,NaN,NaN,NaN,NaN,...,2300.0,2200.0,2200.0,2200.0,2200.0,2225.0,2300.0,2300.0,2300.0,Higher-Income
62,11358,New York,NY,"New York, NY",Queens,580,NaN,NaN,NaN,NaN,...,2200.0,2200.0,2200.0,2100.0,2147.5,2300.0,2300.0,2300.0,2300.0,Higher-Income
63,10030,New York,NY,"New York, NY",New York,583,NaN,NaN,NaN,NaN,...,1537.5,1627.5,1550.0,1550.0,1625.0,1600.0,1695.0,1600.0,1595.0,Gentrifying
64,10017,New York,NY,"New York, NY",New York,617,NaN,NaN,NaN,NaN,...,2497.0,2500.0,2550.0,2580.0,2575.0,2580.0,2600.0,2650.0,2600.0,Higher-Income
65,10038,New York,NY,"New York, NY",New York,630,NaN,NaN,NaN,NaN,...,2935.0,2837.5,2878.5,2940.5,2950.0,2950.0,3000.0,3100.0,3125.0,Gentrifying
66,11379,New York,NY,"New York, NY",Queens,635,NaN,NaN,NaN,NaN,...,1975.0,2000.0,2000.0,2200.0,2150.0,2000.0,2000.0,2000.0,2100.0,Higher-Income
67,10037,New York,NY,"New York, NY",New York,664,NaN,NaN,NaN,NaN,...,1599.5,1655.0,1650.0,1630.0,1650.0,1680.0,1682.0,1700.0,1695.0,Gentrifying
68,11361,New York,NY,"New York, NY",Queens,712,NaN,NaN,NaN,NaN,...,2200.0,2199.5,2200.0,2200.0,2200.0,2199.5,2200.0,2400.0,2300.0,Higher-Income
69,11378,New York,NY,"New York, NY",Queens,726,NaN,NaN,NaN,NaN,...,1925.0,2100.0,2100.0,2150.0,2200.0,2150.0,2100.0,2100.0,2125.0,Higher-Income
70,11360,New York,NY,"New York, NY",Queens,745,NaN,NaN,NaN,NaN,...,2350.0,2350.0,2350.0,2300.0,2250.0,2300.0,2350.0,2350.0,2350.0,Higher-Income
71,11356,New York,NY,"New York, NY",Queens,808,NaN,NaN,NaN,NaN,...,2000.0,1975.0,2100.0,2200.0,2200.0,2195.0,2200.0,2300.0,2200.0,Higher-Income
72,10005,New York,NY,"New York, NY",New York,825,NaN,NaN,NaN,NaN,...,3104.0,3150.0,3207.0,3137.0,3087.0,3190.0,3250.0,3253.0,3302.0,Gentrifying
73,10018,New York,NY,"New York, NY",New York,826,NaN,NaN,NaN,NaN,...,2752.5,2755.0,2755.0,2807.5,2850.0,2755.0,2865.0,2852.5,2970.0,Higher-Income
74,10280,New York,NY,"New York, NY",New York,833,NaN,NaN,NaN,NaN,...,3220.0,3400.0,3400.0,3300.0,3325.0,3400.0,3400.0,3390.0,3500.0,Higher-Income
75,11109,New York,NY,"New York, NY",Queens,838,NaN,NaN,NaN,NaN,...,2237.5,2260.0,2300.0,2340.0,2330.0,2340.0,2340.0,2342.5,2400.0,Higher-Income
76,10069,New York,NY,"New York, NY",New York,843,NaN,NaN,NaN,NaN,...,3075.0,3125.0,3288.0,3288.0,3160.0,3220.0,3467.5,3500.0,3400.0,Higher-Income
77,10006,New York,NY,"New York, NY",New York,849,NaN,NaN,NaN,NaN,...,2912.5,2845.0,3041.0,3000.0,3047.0,3092.5,2965.0,3032.5,2982.5,Higher-Income
78,10004,New York,NY,"New York, NY",New York,850,NaN,NaN,NaN,NaN,...,3500.0,3595.0,3375.0,2987.0,2850.0,3350.0,3250.0,3050.0,3138.0,Higher-Income

In [36]:
df_gent1['gentrification_label'].unique()
df_gent2['2011-06'].unique()

array([1795. , 2500. ,    nan, 1700. , 2350. , 1900. , 1827.5, 2300. ,
       2425. , 2085. , 2553.5, 1600. , 1625. , 1257.5, 2595. , 2797.5,
       2450. , 2397.5, 2585. , 2330.5])

In [44]:
df_gent2 = df_gent1.dropna(axis = 1, thresh =30 , how = 'all')
df_gent2

,RegionName,City,State,Metro,CountyName,SizeRank,2011-11,2011-12,2012-01,2012-02,...,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,gentrification_label
Id,,,,,,,,,,,,,,,,,,,,,
0,10025,New York,NY,"New York, NY",New York,1,1900.0,1900.0,1895.0,1900.0,...,2618.0,2600.0,2600.0,2695.0,2625.0,2650.0,2700.0,2659.5,2450.0,Higher-Income
1,10023,New York,NY,"New York, NY",New York,3,2295.0,2200.0,2292.5,2295.0,...,2800.0,2893.0,2900.0,2800.0,2800.0,2850.0,2800.0,2770.0,2695.0,Higher-Income
2,10002,New York,NY,"New York, NY",New York,6,NaN,NaN,NaN,NaN,...,2400.0,2272.5,2199.0,2199.5,2227.5,2500.0,2500.0,2295.0,2312.5,Gentrifying
3,10467,New York,NY,"New York, NY",Bronx,8,NaN,NaN,950.0,950.0,...,1275.0,1375.0,1450.0,1450.0,1425.0,1400.0,1362.5,1500.0,1500.0,Non-Gentrifying
4,11226,New York,NY,"New York, NY",Kings,10,NaN,NaN,NaN,NaN,...,1500.0,1597.0,1550.0,1525.0,1525.0,1550.0,1550.0,1645.0,1600.0,Higher-Income
5,11375,New York,NY,"New York, NY",Queens,11,1325.0,1300.0,1300.0,1325.0,...,1695.0,1690.0,1725.0,1800.0,1800.0,1795.0,1785.0,1695.0,1925.0,Higher-Income
6,10016,New York,NY,"New York, NY",New York,12,2300.0,2275.0,2299.5,2300.0,...,2695.0,2750.0,2750.0,2787.5,2795.0,2800.0,2775.0,2775.0,2750.0,Higher-Income
7,11235,New York,NY,"New York, NY",Kings,13,NaN,NaN,NaN,NaN,...,1700.0,1695.0,1550.0,1650.0,1699.5,1700.0,1632.5,1695.0,1725.0,Higher-Income
8,10009,New York,NY,"New York, NY",New York,14,1900.0,1900.0,1925.0,1925.0,...,2100.0,2100.0,2100.0,2136.0,2150.0,2199.0,2195.0,2150.0,2200.0,Gentrifying
9,10029,New York,NY,"New York, NY",New York,15,NaN,NaN,NaN,NaN,...,2800.0,2750.0,2775.0,2800.0,2750.0,2800.0,2812.5,2800.0,2750.0,Gentrifying
10,10128,New York,NY,"New York, NY",New York,16,1950.0,1900.0,1875.0,1862.5,...,2250.0,2249.0,2150.0,2175.0,2200.0,2179.0,2150.0,2150.0,2137.5,Higher-Income
11,10011,New York,NY,"New York, NY",New York,17,2500.0,2500.0,2490.0,2495.0,...,2860.0,2850.0,2850.0,2895.0,2900.0,2900.0,2950.0,2950.0,2950.0,Higher-Income
12,10003,New York,NY,"New York, NY",New York,22,2495.0,2350.0,2375.0,2495.0,...,2675.0,2700.0,2725.0,2800.0,2800.0,2700.0,2800.0,2750.0,2695.0,Gentrifying
13,10462,New York,NY,"New York, NY",Bronx,23,NaN,NaN,NaN,NaN,...,1399.0,1400.0,1435.0,1495.0,1500.0,1550.0,1500.0,1500.0,1500.0,Higher-Income
14,11209,New York,NY,"New York, NY",Kings,30,NaN,1100.0,1100.0,1175.0,...,1450.0,1650.0,1605.0,1575.0,1497.5,1672.5,1695.0,1750.0,1725.0,Higher-Income
15,11201,New York,NY,"New York, NY",Kings,31,NaN,NaN,2200.0,2225.0,...,2500.0,2562.0,2542.0,2564.0,2543.0,2584.0,2666.0,2715.0,2704.0,Higher-Income
16,10024,New York,NY,"New York, NY",New York,34,2095.0,2100.0,2025.0,2050.0,...,2397.5,2330.0,2350.0,2395.0,2400.0,2450.0,2400.0,2437.5,2397.5,Higher-Income
17,11214,New York,NY,"New York, NY",Kings,37,NaN,NaN,NaN,NaN,...,1750.0,1750.0,1787.5,1875.0,1900.0,2000.0,2000.0,1950.0,1800.0,Higher-Income
18,10458,New York,NY,"New York, NY",Bronx,42,NaN,NaN,NaN,NaN,...,1325.0,1312.5,1350.0,1450.0,1400.0,1425.0,1350.0,1400.0,1395.0,Non-Gentrifying
19,11234,New York,NY,"New York, NY",Kings,43,NaN,NaN,NaN,NaN,...,1800.0,2050.0,2000.0,2000.0,2000.0,2250.0,2000.0,2000.0,1950.0,Higher-Income
20,10019,New York,NY,"New York, NY",New York,44,2500.0,2497.5,2500.0,2540.0,...,2900.0,2880.0,2900.0,2925.0,2900.5,3000.0,2995.0,3000.0,3010.0,Higher-Income
21,11355,New York,NY,"New York, NY",Queens,48,1253.0,1350.0,1300.0,1367.0,...,1700.0,1725.0,1700.0,1700.0,1950.0,2100.0,2050.0,1950.0,1900.0,Higher-Income
22,11215,New York,NY,"New York, NY",Kings,52,NaN,NaN,NaN,NaN,...,2300.0,2500.0,2369.0,2300.0,2250.0,2200.0,2225.0,2200.0,2400.0,Higher-Income
23,11221,New York,NY,"New York, NY",Kings,53,1435.0,1450.0,1350.0,1450.0,...,1950.0,2000.0,1800.0,1800.0,1850.0,2000.0,2175.0,1999.5,2000.0,Gentrifying
24,11211,New York,NY,"New York, NY",Kings,60,2250.0,2400.0,2600.0,2224.5,...,2830.0,2745.0,2745.0,2710.0,2750.0,2750.0,2692.5,2750.0,2790.0,Gentrifying
25,11373,New York,NY,"New York, NY",Queens,61,1195.0,1195.0,1225.0,1225.0,...,1472.5,1550.0,1650.0,1605.0,1512.0,1475.0,1500.0,1581.0,1600.0,Higher-Income
26,11385,New York,NY,"New York, NY",Queens,61,NaN,NaN,NaN,NaN,...,2150.0,2300.0,2000.0,2075.0,2000.0,2000.0,2000.0,2050.0,2100.0,Higher-Income
27,10468,New York,NY,"New York, NY",Bronx,65,NaN,NaN,NaN,NaN,...,1375.0,1412.5,1400.0,1375.0,1350.0,1375.0,1395.0,1395.0,1350.0,Non-Gentrifying
28,10028,New York,NY,"New York, NY",New York,66,1895.0,1875.0,1865.0,1850.0,...,1995.0,2063.0,2095.0,2100.0,2095.0,2150.0,2125.0,2100.0,2100.0,Higher-Income
29,10027,New York,NY,"New York, NY",New York,75,NaN,NaN,NaN,NaN,...,2025.0,2100.0,2250.0,2147.5,2015.5,1950.0,1895.0,2025.0,2045.5,Gentrifying
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,10065,New York,NY,"New York, NY",New York,313,2495.0,2337.5,2295.0,2350.0,...,2730.0,2695.0,2795.0,2700.0,2700.0,2762.5,2850.0,2800.0,2625.0,Higher-Income
50,11435,New York,NY,"New York, NY",Queens,338,NaN,NaN,NaN,NaN,...,1475.0,1475.0,1499.0,1599.5,1675.0,1695.0,1600.0,1612.5,1599.5,Higher-Income
51,11205,New York,NY,"New York, NY",Kings,357,NaN,NaN,NaN,NaN,...,2350.0,2380.0,2261.0,2261.0,2352.0,2397.5,2395.0,2397.5,2400.0,Higher-Income
52,11217,New York,NY,"New York, NY",Kings,399,NaN,NaN,NaN,NaN,...,2535.0,2431.5,2340.0,2350.0,2580.0,2655.0,2745.0,2723.0,2710.0,Higher-Income
53,11365,New York,NY,"New York, NY",Queens,401,NaN,NaN,NaN,NaN,...,2400.0,2300.0,2300.0,2297.5,2200.0,2300.0,2375.0,2450.0,2500.0,Higher-Income
54,10035,New York,NY,"New York, NY",New York,428,1787.0,1742.5,1650.0,1650.0,...,1850.0,1743.5,1855.0,1795.0,1772.5,1850.0,1795.0,1922.5,1885.0,Gentrifying
55,10075,New York,NY,"New York, NY",New York,433,1775.0,1775.0,1750.0,1795.0,...,2000.0,1950.0,1973.5,1997.0,1995.0,2000.0,2075.0,2075.0,2050.0,Higher-Income
56,11102,New York,NY,"New York, NY",Queens,434,NaN,NaN,NaN,NaN,...,2000.0,2050.0,2000.0,2000.0,1932.0,1995.0,1837.5,2100.0,2100.0,Gentrifying
57,11101,New York,NY,"New York, NY",Queens,439,NaN,NaN,NaN,NaN,...,2235.0,2251.0,2238.5,2271.0,2315.0,2347.5,2416.0,2418.0,2400.0,Higher-Income
58,10001,New York,NY,"New York, NY",New York,466,NaN,NaN,NaN,2455.0,...,2987.5,3037.0,2995.5,2907.0,2999.5,3177.0,3080.0,3077.0,3074.5,Higher-Income
59,10012,New York,NY,"New York, NY",New York,472,NaN,NaN,2350.0,2395.0,...,2750.0,2750.0,2800.0,2892.5,2895.0,3000.0,2890.0,2882.5,2870.0,Higher-Income
60,11249,New York,NY,"New York, NY",Kings,488,NaN,NaN,NaN,NaN,...,2865.0,2995.0,2995.0,2939.5,2950.0,2953.0,2950.0,3193.0,3200.0,Gentrifying
61,11357,New York,NY,"New York, NY",Queens,512,NaN,NaN,NaN,NaN,...,2300.0,2200.0,2200.0,2200.0,2200.0,2225.0,2300.0,2300.0,2300.0,Higher-Income
62,11358,New York,NY,"New York, NY",Queens,580,NaN,NaN,NaN,NaN,...,2200.0,2200.0,2200.0,2100.0,2147.5,2300.0,2300.0,2300.0,2300.0,Higher-Income
63,10030,New York,NY,"New York, NY",New York,583,NaN,NaN,NaN,NaN,...,1537.5,1627.5,1550.0,1550.0,1625.0,1600.0,1695.0,1600.0,1595.0,Gentrifying
64,10017,New York,NY,"New York, NY",New York,617,2300.0,2200.0,2200.0,2275.0,...,2497.0,2500.0,2550.0,2580.0,2575.0,2580.0,2600.0,2650.0,2600.0,Higher-Income
65,10038,New York,NY,"New York, NY",New York,630,2516.5,2550.0,2550.0,2545.0,...,2935.0,2837.5,2878.5,2940.5,2950.0,2950.0,3000.0,3100.0,3125.0,Gentrifying
66,11379,New York,NY,"New York, NY",Queens,635,NaN,NaN,NaN,NaN,...,1975.0,2000.0,2000.0,2200.0,2150.0,2000.0,2000.0,2000.0,2100.0,Higher-Income
67,10037,New York,NY,"New York, NY",New York,664,NaN,NaN,NaN,NaN,...,1599.5,1655.0,1650.0,1630.0,1650.0,1680.0,1682.0,1700.0,1695.0,Gentrifying
68,11361,New York,NY,"New York, NY",Queens,712,NaN,NaN,NaN,NaN,...,2200.0,2199.5,2200.0,2200.0,2200.0,2199.5,2200.0,2400.0,2300.0,Higher-Income
69,11378,New York,NY,"New York, NY",Queens,726,NaN,NaN,NaN,NaN,...,1925.0,2100.0,2100.0,2150.0,2200.0,2150.0,2100.0,2100.0,2125.0,Higher-Income
70,11360,New York,NY,"New York, NY",Queens,745,NaN,NaN,NaN,NaN,...,2350.0,2350.0,2350.0,2300.0,2250.0,2300.0,2350.0,2350.0,2350.0,Higher-Income
71,11356,New York,NY,"New York, NY",Queens,808,NaN,NaN,NaN,NaN,...,2000.0,1975.0,2100.0,2200.0,2200.0,2195.0,2200.0,2300.0,2200.0,Higher-Income
72,10005,New York,NY,"New York, NY",New York,825,2695.0,2599.0,2600.0,2600.0,...,3104.0,3150.0,3207.0,3137.0,3087.0,3190.0,3250.0,3253.0,3302.0,Gentrifying
73,10018,New York,NY,"New York, NY",New York,826,NaN,2313.5,2200.0,2415.0,...,2752.5,2755.0,2755.0,2807.5,2850.0,2755.0,2865.0,2852.5,2970.0,Higher-Income
74,10280,New York,NY,"New York, NY",New York,833,2750.0,2800.0,2795.0,2700.0,...,3220.0,3400.0,3400.0,3300.0,3325.0,3400.0,3400.0,3390.0,3500.0,Higher-Income
75,11109,New York,NY,"New York, NY",Queens,838,NaN,NaN,NaN,NaN,...,2237.5,2260.0,2300.0,2340.0,2330.0,2340.0,2340.0,2342.5,2400.0,Higher-Income
76,10069,New York,NY,"New York, NY",New York,843,3050.0,2885.0,2855.0,2800.0,...,3075.0,3125.0,3288.0,3288.0,3160.0,3220.0,3467.5,3500.0,3400.0,Higher-Income
77,10006,New York,NY,"New York, NY",New York,849,2500.0,2445.5,2445.0,2499.5,...,2912.5,2845.0,3041.0,3000.0,3047.0,3092.5,2965.0,3032.5,2982.5,Higher-Income
78,10004,New York,NY,"New York, NY",New York,850,NaN,NaN,NaN,NaN,...,3500.0,3595.0,3375.0,2987.0,2850.0,3350.0,3250.0,3050.0,3138.0,Higher-Income

In [46]:
# df_gent_final = df_gent2.drop('RegionName', 1)
df_gent_final = df_gent2.drop('City', 1)
df_gent_final = df_gent_final.drop('State', 1)
df_gent_final = df_gent_final.drop('Metro', 1)
df_gent_final['RegionName'] = df_gent_final.RegionName.astype('category')
df_gent_final['CountyName'] = df_gent_final.CountyName.astype('category')
df_gent_final['SizeRank'] = df_gent_final.SizeRank.astype('category')
df_gent_final['gentrification_label'] = df_gent_final.gentrification_label.astype('category')

,RegionName,CountyName,SizeRank,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,...,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,gentrification_label
Id,,,,,,,,,,,,,,,,,,,,,
0,10025,New York,1,1900.0,1900.0,1895.0,1900.0,1875.0,1900.0,1900.0,...,2618.0,2600.0,2600.0,2695.0,2625.0,2650.0,2700.0,2659.5,2450.0,Higher-Income
1,10023,New York,3,2295.0,2200.0,2292.5,2295.0,2200.0,2245.0,2250.0,...,2800.0,2893.0,2900.0,2800.0,2800.0,2850.0,2800.0,2770.0,2695.0,Higher-Income
2,10002,New York,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2400.0,2272.5,2199.0,2199.5,2227.5,2500.0,2500.0,2295.0,2312.5,Gentrifying
3,10467,Bronx,8,NaN,NaN,950.0,950.0,950.0,925.0,950.0,...,1275.0,1375.0,1450.0,1450.0,1425.0,1400.0,1362.5,1500.0,1500.0,Non-Gentrifying
4,11226,Kings,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500.0,1597.0,1550.0,1525.0,1525.0,1550.0,1550.0,1645.0,1600.0,Higher-Income
5,11375,Queens,11,1325.0,1300.0,1300.0,1325.0,1337.5,1350.0,1350.0,...,1695.0,1690.0,1725.0,1800.0,1800.0,1795.0,1785.0,1695.0,1925.0,Higher-Income
6,10016,New York,12,2300.0,2275.0,2299.5,2300.0,2300.0,2295.0,2300.0,...,2695.0,2750.0,2750.0,2787.5,2795.0,2800.0,2775.0,2775.0,2750.0,Higher-Income
7,11235,Kings,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1700.0,1695.0,1550.0,1650.0,1699.5,1700.0,1632.5,1695.0,1725.0,Higher-Income
8,10009,New York,14,1900.0,1900.0,1925.0,1925.0,1900.0,1950.0,1950.0,...,2100.0,2100.0,2100.0,2136.0,2150.0,2199.0,2195.0,2150.0,2200.0,Gentrifying
9,10029,New York,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2800.0,2750.0,2775.0,2800.0,2750.0,2800.0,2812.5,2800.0,2750.0,Gentrifying
10,10128,New York,16,1950.0,1900.0,1875.0,1862.5,1850.0,1850.0,1875.0,...,2250.0,2249.0,2150.0,2175.0,2200.0,2179.0,2150.0,2150.0,2137.5,Higher-Income
11,10011,New York,17,2500.0,2500.0,2490.0,2495.0,2400.0,2450.0,2600.0,...,2860.0,2850.0,2850.0,2895.0,2900.0,2900.0,2950.0,2950.0,2950.0,Higher-Income
12,10003,New York,22,2495.0,2350.0,2375.0,2495.0,2475.0,2495.0,2495.0,...,2675.0,2700.0,2725.0,2800.0,2800.0,2700.0,2800.0,2750.0,2695.0,Gentrifying
13,10462,Bronx,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1399.0,1400.0,1435.0,1495.0,1500.0,1550.0,1500.0,1500.0,1500.0,Higher-Income
14,11209,Kings,30,NaN,1100.0,1100.0,1175.0,1200.0,1200.0,1200.0,...,1450.0,1650.0,1605.0,1575.0,1497.5,1672.5,1695.0,1750.0,1725.0,Higher-Income
15,11201,Kings,31,NaN,NaN,2200.0,2225.0,2200.0,2200.0,2159.0,...,2500.0,2562.0,2542.0,2564.0,2543.0,2584.0,2666.0,2715.0,2704.0,Higher-Income
16,10024,New York,34,2095.0,2100.0,2025.0,2050.0,2100.0,2100.0,2100.0,...,2397.5,2330.0,2350.0,2395.0,2400.0,2450.0,2400.0,2437.5,2397.5,Higher-Income
17,11214,Kings,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1750.0,1750.0,1787.5,1875.0,1900.0,2000.0,2000.0,1950.0,1800.0,Higher-Income
18,10458,Bronx,42,NaN,NaN,NaN,NaN,NaN,875.0,900.0,...,1325.0,1312.5,1350.0,1450.0,1400.0,1425.0,1350.0,1400.0,1395.0,Non-Gentrifying
19,11234,Kings,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1800.0,2050.0,2000.0,2000.0,2000.0,2250.0,2000.0,2000.0,1950.0,Higher-Income
20,10019,New York,44,2500.0,2497.5,2500.0,2540.0,2500.0,2500.0,2604.5,...,2900.0,2880.0,2900.0,2925.0,2900.5,3000.0,2995.0,3000.0,3010.0,Higher-Income
21,11355,Queens,48,1253.0,1350.0,1300.0,1367.0,1400.0,1300.0,1300.0,...,1700.0,1725.0,1700.0,1700.0,1950.0,2100.0,2050.0,1950.0,1900.0,Higher-Income
22,11215,Kings,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2300.0,2500.0,2369.0,2300.0,2250.0,2200.0,2225.0,2200.0,2400.0,Higher-Income
23,11221,Kings,53,1435.0,1450.0,1350.0,1450.0,1520.0,1400.0,1500.0,...,1950.0,2000.0,1800.0,1800.0,1850.0,2000.0,2175.0,1999.5,2000.0,Gentrifying
24,11211,Kings,60,2250.0,2400.0,2600.0,2224.5,2400.0,2600.0,2650.0,...,2830.0,2745.0,2745.0,2710.0,2750.0,2750.0,2692.5,2750.0,2790.0,Gentrifying
25,11373,Queens,61,1195.0,1195.0,1225.0,1225.0,1225.0,1225.0,1220.0,...,1472.5,1550.0,1650.0,1605.0,1512.0,1475.0,1500.0,1581.0,1600.0,Higher-Income
26,11385,Queens,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2150.0,2300.0,2000.0,2075.0,2000.0,2000.0,2000.0,2050.0,2100.0,Higher-Income
27,10468,Bronx,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1375.0,1412.5,1400.0,1375.0,1350.0,1375.0,1395.0,1395.0,1350.0,Non-Gentrifying
28,10028,New York,66,1895.0,1875.0,1865.0,1850.0,1850.0,1850.0,1850.0,...,1995.0,2063.0,2095.0,2100.0,2095.0,2150.0,2125.0,2100.0,2100.0,Higher-Income
29,10027,New York,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2025.0,2100.0,2250.0,2147.5,2015.5,1950.0,1895.0,2025.0,2045.5,Gentrifying
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,10065,New York,313,2495.0,2337.5,2295.0,2350.0,2300.0,2200.0,2400.0,...,2730.0,2695.0,2795.0,2700.0,2700.0,2762.5,2850.0,2800.0,2625.0,Higher-Income
50,11435,Queens,338,NaN,NaN,NaN,NaN,1300.0,1200.0,1197.5,...,1475.0,1475.0,1499.0,1599.5,1675.0,1695.0,1600.0,1612.5,1599.5,Higher-Income
51,11205,Kings,357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2350.0,2380.0,2261.0,2261.0,2352.0,2397.5,2395.0,2397.5,2400.0,Higher-Income
52,11217,Kings,399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2535.0,2431.5,2340.0,2350.0,2580.0,2655.0,2745.0,2723.0,2710.0,Higher-Income
53,11365,Queens,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2400.0,2300.0,2300.0,2297.5,2200.0,2300.0,2375.0,2450.0,2500.0,Higher-Income
54,10035,New York,428,1787.0,1742.5,1650.0,1650.0,1687.0,1749.0,1770.5,...,1850.0,1743.5,1855.0,1795.0,1772.5,1850.0,1795.0,1922.5,1885.0,Gentrifying
55,10075,New York,433,1775.0,1775.0,1750.0,1795.0,1800.0,1800.0,1850.0,...,2000.0,1950.0,1973.5,1997.0,1995.0,2000.0,2075.0,2075.0,2050.0,Higher-Income
56,11102,Queens,434,NaN,NaN,NaN,NaN,1600.0,1650.0,1650.0,...,2000.0,2050.0,2000.0,2000.0,1932.0,1995.0,1837.5,2100.0,2100.0,Gentrifying
57,11101,Queens,439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2235.0,2251.0,2238.5,2271.0,2315.0,2347.5,2416.0,2418.0,2400.0,Higher-Income
58,10001,New York,466,NaN,NaN,NaN,2455.0,2500.0,2600.0,2600.0,...,2987.5,3037.0,2995.5,2907.0,2999.5,3177.0,3080.0,3077.0,3074.5,Higher-Income
59,10012,New York,472,NaN,NaN,2350.0,2395.0,2495.0,2450.0,2450.0,...,2750.0,2750.0,2800.0,2892.5,2895.0,3000.0,2890.0,2882.5,2870.0,Higher-Income
60,11249,Kings,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2865.0,2995.0,2995.0,2939.5,2950.0,2953.0,2950.0,3193.0,3200.0,Gentrifying
61,11357,Queens,512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2300.0,2200.0,2200.0,2200.0,2200.0,2225.0,2300.0,2300.0,2300.0,Higher-Income
62,11358,Queens,580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2200.0,2200.0,2200.0,2100.0,2147.5,2300.0,2300.0,2300.0,2300.0,Higher-Income
63,10030,New York,583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1537.5,1627.5,1550.0,1550.0,1625.0,1600.0,1695.0,1600.0,1595.0,Gentrifying
64,10017,New York,617,2300.0,2200.0,2200.0,2275.0,2300.0,2295.0,2300.0,...,2497.0,2500.0,2550.0,2580.0,2575.0,2580.0,2600.0,2650.0,2600.0,Higher-Income
65,10038,New York,630,2516.5,2550.0,2550.0,2545.0,2530.0,2550.0,2550.0,...,2935.0,2837.5,2878.5,2940.5,2950.0,2950.0,3000.0,3100.0,3125.0,Gentrifying
66,11379,Queens,635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1975.0,2000.0,2000.0,2200.0,2150.0,2000.0,2000.0,2000.0,2100.0,Higher-Income
67,10037,New York,664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1599.5,1655.0,1650.0,1630.0,1650.0,1680.0,1682.0,1700.0,1695.0,Gentrifying
68,11361,Queens,712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2200.0,2199.5,2200.0,2200.0,2200.0,2199.5,2200.0,2400.0,2300.0,Higher-Income
69,11378,Queens,726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1925.0,2100.0,2100.0,2150.0,2200.0,2150.0,2100.0,2100.0,2125.0,Higher-Income
70,11360,Queens,745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2350.0,2350.0,2350.0,2300.0,2250.0,2300.0,2350.0,2350.0,2350.0,Higher-Income
71,11356,Queens,808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2000.0,1975.0,2100.0,2200.0,2200.0,2195.0,2200.0,2300.0,2200.0,Higher-Income
72,10005,New York,825,2695.0,2599.0,2600.0,2600.0,2637.0,2650.0,2700.0,...,3104.0,3150.0,3207.0,3137.0,3087.0,3190.0,3250.0,3253.0,3302.0,Gentrifying
73,10018,New York,826,NaN,2313.5,2200.0,2415.0,2430.0,2495.0,2560.0,...,2752.5,2755.0,2755.0,2807.5,2850.0,2755.0,2865.0,2852.5,2970.0,Higher-Income
74,10280,New York,833,2750.0,2800.0,2795.0,2700.0,2800.0,2800.0,2800.0,...,3220.0,3400.0,3400.0,3300.0,3325.0,3400.0,3400.0,3390.0,3500.0,Higher-Income
75,11109,Queens,838,NaN,NaN,NaN,NaN,2242.5,2215.0,2252.5,...,2237.5,2260.0,2300.0,2340.0,2330.0,2340.0,2340.0,2342.5,2400.0,Higher-Income
76,10069,New York,843,3050.0,2885.0,2855.0,2800.0,2810.0,2710.0,2820.0,...,3075.0,3125.0,3288.0,3288.0,3160.0,3220.0,3467.5,3500.0,3400.0,Higher-Income
77,10006,New York,849,2500.0,2445.5,2445.0,2499.5,2450.0,2400.0,2425.0,...,2912.5,2845.0,3041.0,3000.0,3047.0,3092.5,2965.0,3032.5,2982.5,Higher-Income
78,10004,New York,850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3500.0,3595.0,3375.0,2987.0,2850.0,3350.0,3250.0,3050.0,3138.0,Higher-Income

In [57]:
blankIndex=[''] * len(df_gent_final)
df_gent_final.index=blankIndex
df_gent_final

,RegionName,CountyName,SizeRank,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,...,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,gentrification_label
,10025,New York,1,1900.0,1900.0,1895.0,1900.0,1875.0,1900.0,1900.0,...,2618.0,2600.0,2600.0,2695.0,2625.0,2650.0,2700.0,2659.5,2450.0,Higher-Income
,10023,New York,3,2295.0,2200.0,2292.5,2295.0,2200.0,2245.0,2250.0,...,2800.0,2893.0,2900.0,2800.0,2800.0,2850.0,2800.0,2770.0,2695.0,Higher-Income
,10002,New York,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2400.0,2272.5,2199.0,2199.5,2227.5,2500.0,2500.0,2295.0,2312.5,Gentrifying
,10467,Bronx,8,NaN,NaN,950.0,950.0,950.0,925.0,950.0,...,1275.0,1375.0,1450.0,1450.0,1425.0,1400.0,1362.5,1500.0,1500.0,Non-Gentrifying
,11226,Kings,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500.0,1597.0,1550.0,1525.0,1525.0,1550.0,1550.0,1645.0,1600.0,Higher-Income
,11375,Queens,11,1325.0,1300.0,1300.0,1325.0,1337.5,1350.0,1350.0,...,1695.0,1690.0,1725.0,1800.0,1800.0,1795.0,1785.0,1695.0,1925.0,Higher-Income
,10016,New York,12,2300.0,2275.0,2299.5,2300.0,2300.0,2295.0,2300.0,...,2695.0,2750.0,2750.0,2787.5,2795.0,2800.0,2775.0,2775.0,2750.0,Higher-Income
,11235,Kings,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1700.0,1695.0,1550.0,1650.0,1699.5,1700.0,1632.5,1695.0,1725.0,Higher-Income
,10009,New York,14,1900.0,1900.0,1925.0,1925.0,1900.0,1950.0,1950.0,...,2100.0,2100.0,2100.0,2136.0,2150.0,2199.0,2195.0,2150.0,2200.0,Gentrifying
,10029,New York,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2800.0,2750.0,2775.0,2800.0,2750.0,2800.0,2812.5,2800.0,2750.0,Gentrifying
,10128,New York,16,1950.0,1900.0,1875.0,1862.5,1850.0,1850.0,1875.0,...,2250.0,2249.0,2150.0,2175.0,2200.0,2179.0,2150.0,2150.0,2137.5,Higher-Income
,10011,New York,17,2500.0,2500.0,2490.0,2495.0,2400.0,2450.0,2600.0,...,2860.0,2850.0,2850.0,2895.0,2900.0,2900.0,2950.0,2950.0,2950.0,Higher-Income
,10003,New York,22,2495.0,2350.0,2375.0,2495.0,2475.0,2495.0,2495.0,...,2675.0,2700.0,2725.0,2800.0,2800.0,2700.0,2800.0,2750.0,2695.0,Gentrifying
,10462,Bronx,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1399.0,1400.0,1435.0,1495.0,1500.0,1550.0,1500.0,1500.0,1500.0,Higher-Income
,11209,Kings,30,NaN,1100.0,1100.0,1175.0,1200.0,1200.0,1200.0,...,1450.0,1650.0,1605.0,1575.0,1497.5,1672.5,1695.0,1750.0,1725.0,Higher-Income
,11201,Kings,31,NaN,NaN,2200.0,2225.0,2200.0,2200.0,2159.0,...,2500.0,2562.0,2542.0,2564.0,2543.0,2584.0,2666.0,2715.0,2704.0,Higher-Income
,10024,New York,34,2095.0,2100.0,2025.0,2050.0,2100.0,2100.0,2100.0,...,2397.5,2330.0,2350.0,2395.0,2400.0,2450.0,2400.0,2437.5,2397.5,Higher-Income
,11214,Kings,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1750.0,1750.0,1787.5,1875.0,1900.0,2000.0,2000.0,1950.0,1800.0,Higher-Income
,10458,Bronx,42,NaN,NaN,NaN,NaN,NaN,875.0,900.0,...,1325.0,1312.5,1350.0,1450.0,1400.0,1425.0,1350.0,1400.0,1395.0,Non-Gentrifying
,11234,Kings,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1800.0,2050.0,2000.0,2000.0,2000.0,2250.0,2000.0,2000.0,1950.0,Higher-Income
,10019,New York,44,2500.0,2497.5,2500.0,2540.0,2500.0,2500.0,2604.5,...,2900.0,2880.0,2900.0,2925.0,2900.5,3000.0,2995.0,3000.0,3010.0,Higher-Income
,11355,Queens,48,1253.0,1350.0,1300.0,1367.0,1400.0,1300.0,1300.0,...,1700.0,1725.0,1700.0,1700.0,1950.0,2100.0,2050.0,1950.0,1900.0,Higher-Income
,11215,Kings,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2300.0,2500.0,2369.0,2300.0,2250.0,2200.0,2225.0,2200.0,2400.0,Higher-Income
,11221,Kings,53,1435.0,1450.0,1350.0,1450.0,1520.0,1400.0,1500.0,...,1950.0,2000.0,1800.0,1800.0,1850.0,2000.0,2175.0,1999.5,2000.0,Gentrifying
,11211,Kings,60,2250.0,2400.0,2600.0,2224.5,2400.0,2600.0,2650.0,...,2830.0,2745.0,2745.0,2710.0,2750.0,2750.0,2692.5,2750.0,2790.0,Gentrifying
,11373,Queens,61,1195.0,1195.0,1225.0,1225.0,1225.0,1225.0,1220.0,...,1472.5,1550.0,1650.0,1605.0,1512.0,1475.0,1500.0,1581.0,1600.0,Higher-Income
,11385,Queens,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2150.0,2300.0,2000.0,2075.0,2000.0,2000.0,2000.0,2050.0,2100.0,Higher-Income
,10468,Bronx,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1375.0,1412.5,1400.0,1375.0,1350.0,1375.0,1395.0,1395.0,1350.0,Non-Gentrifying
,10028,New York,66,1895.0,1875.0,1865.0,1850.0,1850.0,1850.0,1850.0,...,1995.0,2063.0,2095.0,2100.0,2095.0,2150.0,2125.0,2100.0,2100.0,Higher-Income
,10027,New York,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2025.0,2100.0,2250.0,2147.5,2015.5,1950.0,1895.0,2025.0,2045.5,Gentrifying
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
,10065,New York,313,2495.0,2337.5,2295.0,2350.0,2300.0,2200.0,2400.0,...,2730.0,2695.0,2795.0,2700.0,2700.0,2762.5,2850.0,2800.0,2625.0,Higher-Income
,11435,Queens,338,NaN,NaN,NaN,NaN,1300.0,1200.0,1197.5,...,1475.0,1475.0,1499.0,1599.5,1675.0,1695.0,1600.0,1612.5,1599.5,Higher-Income
,11205,Kings,357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2350.0,2380.0,2261.0,2261.0,2352.0,2397.5,2395.0,2397.5,2400.0,Higher-Income
,11217,Kings,399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2535.0,2431.5,2340.0,2350.0,2580.0,2655.0,2745.0,2723.0,2710.0,Higher-Income
,11365,Queens,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2400.0,2300.0,2300.0,2297.5,2200.0,2300.0,2375.0,2450.0,2500.0,Higher-Income
,10035,New York,428,1787.0,1742.5,1650.0,1650.0,1687.0,1749.0,1770.5,...,1850.0,1743.5,1855.0,1795.0,1772.5,1850.0,1795.0,1922.5,1885.0,Gentrifying
,10075,New York,433,1775.0,1775.0,1750.0,1795.0,1800.0,1800.0,1850.0,...,2000.0,1950.0,1973.5,1997.0,1995.0,2000.0,2075.0,2075.0,2050.0,Higher-Income
,11102,Queens,434,NaN,NaN,NaN,NaN,1600.0,1650.0,1650.0,...,2000.0,2050.0,2000.0,2000.0,1932.0,1995.0,1837.5,2100.0,2100.0,Gentrifying
,11101,Queens,439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2235.0,2251.0,2238.5,2271.0,2315.0,2347.5,2416.0,2418.0,2400.0,Higher-Income
,10001,New York,466,NaN,NaN,NaN,2455.0,2500.0,2600.0,2600.0,...,2987.5,3037.0,2995.5,2907.0,2999.5,3177.0,3080.0,3077.0,3074.5,Higher-Income
,10012,New York,472,NaN,NaN,2350.0,2395.0,2495.0,2450.0,2450.0,...,2750.0,2750.0,2800.0,2892.5,2895.0,3000.0,2890.0,2882.5,2870.0,Higher-Income
,11249,Kings,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2865.0,2995.0,2995.0,2939.5,2950.0,2953.0,2950.0,3193.0,3200.0,Gentrifying
,11357,Queens,512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2300.0,2200.0,2200.0,2200.0,2200.0,2225.0,2300.0,2300.0,2300.0,Higher-Income
,11358,Queens,580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2200.0,2200.0,2200.0,2100.0,2147.5,2300.0,2300.0,2300.0,2300.0,Higher-Income
,10030,New York,583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1537.5,1627.5,1550.0,1550.0,1625.0,1600.0,1695.0,1600.0,1595.0,Gentrifying
,10017,New York,617,2300.0,2200.0,2200.0,2275.0,2300.0,2295.0,2300.0,...,2497.0,2500.0,2550.0,2580.0,2575.0,2580.0,2600.0,2650.0,2600.0,Higher-Income
,10038,New York,630,2516.5,2550.0,2550.0,2545.0,2530.0,2550.0,2550.0,...,2935.0,2837.5,2878.5,2940.5,2950.0,2950.0,3000.0,3100.0,3125.0,Gentrifying
,11379,Queens,635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1975.0,2000.0,2000.0,2200.0,2150.0,2000.0,2000.0,2000.0,2100.0,Higher-Income
,10037,New York,664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1599.5,1655.0,1650.0,1630.0,1650.0,1680.0,1682.0,1700.0,1695.0,Gentrifying
,11361,Queens,712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2200.0,2199.5,2200.0,2200.0,2200.0,2199.5,2200.0,2400.0,2300.0,Higher-Income
,11378,Queens,726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1925.0,2100.0,2100.0,2150.0,2200.0,2150.0,2100.0,2100.0,2125.0,Higher-Income
,11360,Queens,745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2350.0,2350.0,2350.0,2300.0,2250.0,2300.0,2350.0,2350.0,2350.0,Higher-Income
,11356,Queens,808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2000.0,1975.0,2100.0,2200.0,2200.0,2195.0,2200.0,2300.0,2200.0,Higher-Income
,10005,New York,825,2695.0,2599.0,2600.0,2600.0,2637.0,2650.0,2700.0,...,3104.0,3150.0,3207.0,3137.0,3087.0,3190.0,3250.0,3253.0,3302.0,Gentrifying
,10018,New York,826,NaN,2313.5,2200.0,2415.0,2430.0,2495.0,2560.0,...,2752.5,2755.0,2755.0,2807.5,2850.0,2755.0,2865.0,2852.5,2970.0,Higher-Income
,10280,New York,833,2750.0,2800.0,2795.0,2700.0,2800.0,2800.0,2800.0,...,3220.0,3400.0,3400.0,3300.0,3325.0,3400.0,3400.0,3390.0,3500.0,Higher-Income
,11109,Queens,838,NaN,NaN,NaN,NaN,2242.5,2215.0,2252.5,...,2237.5,2260.0,2300.0,2340.0,2330.0,2340.0,2340.0,2342.5,2400.0,Higher-Income
,10069,New York,843,3050.0,2885.0,2855.0,2800.0,2810.0,2710.0,2820.0,...,3075.0,3125.0,3288.0,3288.0,3160.0,3220.0,3467.5,3500.0,3400.0,Higher-Income
,10006,New York,849,2500.0,2445.5,2445.0,2499.5,2450.0,2400.0,2425.0,...,2912.5,2845.0,3041.0,3000.0,3047.0,3092.5,2965.0,3032.5,2982.5,Higher-Income
,10004,New York,850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3500.0,3595.0,3375.0,2987.0,2850.0,3350.0,3250.0,3050.0,3138.0,Higher-Income

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_gent_final.loc[:, df_gent_final.columns != 'gentrification_label'], 
                                                    df_gent_final['gentrification_label'], test_size=0.25)

In [67]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
np.mean(predictions==y_test)